QUESTIONS: dict[str, list[dict]] = {
    "Mathematics": [
        {
            "question_text": "What is the sum of -8 and 5?",
            "options": ["-13", "-3", "3", "13"],
            "correct_index": 1,
            "explanation": "-8 + 5 = -3, since 5 partly cancels the negative value.",
        },
        {
            "question_text": "What is the product of -6 and -7?",
            "options": ["-42", "-13", "13", "42"],
            "correct_index": 3,
            "explanation": "The product of two negative integers is positive: 6 x 7 = 42.",
        },
        {
            "question_text": "Convert the fraction 3/4 into a decimal.",
            "options": ["0.34", "0.43", "0.75", "1.33"],
            "correct_index": 2,
            "explanation": "3 divided by 4 equals 0.75.",
        },
        {
            "question_text": "Simplify: 2.5 + 1.75",
            "options": ["3.25", "4.25", "4.15", "3.75"],
            "correct_index": 1,
            "explanation": "2.50 + 1.75 = 4.25.",
        },
        {
            "question_text": "Find the mean of the data set: 4, 8, 6, 10, 2.",
            "options": ["5", "6", "7", "8"],
            "correct_index": 1,
            "explanation": "Sum = 30, divided by 5 values gives a mean of 6.",
        },
        {
            "question_text": "Solve for x: x + 7 = 15.",
            "options": ["x = 6", "x = 7", "x = 8", "x = 22"],
            "correct_index": 2,
            "explanation": "Subtracting 7 from both sides gives x = 8.",
        },
        {
            "question_text": "Two angles that add up to 90 degrees are called what?",
            "options": ["Supplementary angles", "Complementary angles", "Vertical angles", "Adjacent angles"],
            "correct_index": 1,
            "explanation": "Angles summing to 90 degrees are complementary by definition.",
        },
        {
            "question_text": "In a triangle, the sum of interior angles is always:",
            "options": ["90 degrees", "180 degrees", "270 degrees", "360 degrees"],
            "correct_index": 1,
            "explanation": "The angle sum property of a triangle states its interior angles always total 180 degrees.",
        },
        {
            "question_text": "A shopkeeper buys an item for Rs. 200 and sells it for Rs. 250. What is the profit percentage?",
            "options": ["20%", "25%", "50%", "10%"],
            "correct_index": 1,
            "explanation": "Profit = Rs. 50 on a cost of Rs. 200, which is (50/200) x 100 = 25%.",
        },
        {
            "question_text": "Find the simple interest on Rs. 1000 at 5% per annum for 2 years.",
            "options": ["Rs. 50", "Rs. 100", "Rs. 150", "Rs. 200"],
            "correct_index": 1,
            "explanation": "SI = (P x R x T)/100 = (1000 x 5 x 2)/100 = Rs. 100.",
        },
        {
            "question_text": "Which of the following is a rational number?",
            "options": ["Square root of 2", "Pi", "3/7", "Square root of 5"],
            "correct_index": 2,
            "explanation": "3/7 can be expressed as a ratio of two integers, making it rational.",
        },
        {
            "question_text": "What is the standard tool used to draw a perpendicular bisector in practical geometry?",
            "options": ["Protractor only", "Compass and ruler", "Set square only", "Divider only"],
            "correct_index": 1,
            "explanation": "A perpendicular bisector is constructed using a compass to mark equal arcs and a ruler to draw the line.",
        },
        {
            "question_text": "Find the area of a rectangle with length 12 cm and breadth 5 cm.",
            "options": ["17 cm squared", "34 cm squared", "60 cm squared", "120 cm squared"],
            "correct_index": 2,
            "explanation": "Area of a rectangle = length x breadth = 12 x 5 = 60 cm squared.",
        },
        {
            "question_text": "Simplify the algebraic expression: 5x + 3x - 2x.",
            "options": ["6x", "8x", "10x", "0x"],
            "correct_index": 0,
            "explanation": "5x + 3x - 2x = 6x by combining like terms.",
        },
        {
            "question_text": "What is the value of 2 to the power of 5?",
            "options": ["10", "16", "25", "32"],
            "correct_index": 3,
            "explanation": "2 to the power of 5 = 2x2x2x2x2 = 32.",
        },
        {
            "question_text": "Which of these shapes has point symmetry as well as line symmetry?",
            "options": ["Scalene triangle", "Circle", "Right triangle", "Trapezium"],
            "correct_index": 1,
            "explanation": "A circle has infinite lines of symmetry and also has point symmetry about its centre.",
        },
        {
            "question_text": "What is 15% of 200?",
            "options": ["15", "20", "30", "45"],
            "correct_index": 2,
            "explanation": "15% of 200 = (15/100) x 200 = 30.",
        },
        {
            "question_text": "If a triangle has angles 50 degrees and 60 degrees, what is the third angle?",
            "options": ["60 degrees", "70 degrees", "80 degrees", "90 degrees"],
            "correct_index": 1,
            "explanation": "180 - 50 - 60 = 70 degrees.",
        },
        {
            "question_text": "Which number is a multiplicative inverse of 7?",
            "options": ["-7", "0", "1/7", "7"],
            "correct_index": 2,
            "explanation": "A number multiplied by its multiplicative inverse gives 1; 7 x 1/7 = 1.",
        },
        {
            "question_text": "What is the perimeter of a square with side length 9 cm?",
            "options": ["18 cm", "27 cm", "36 cm", "81 cm"],
            "correct_index": 2,
            "explanation": "Perimeter of a square = 4 x side = 4 x 9 = 36 cm.",
        },
    ],
    "Science": [
        {
            "question_text": "Which of the following is a leguminous plant that helps in nitrogen fixation?",
            "options": ["Wheat", "Rice", "Gram", "Maize"],
            "correct_index": 2,
            "explanation": "Gram is a legume whose root nodules host nitrogen-fixing bacteria.",
        },
        {
            "question_text": "Which type of fibre is nylon?",
            "options": ["Natural fibre", "Synthetic fibre", "Animal fibre", "Plant fibre"],
            "correct_index": 1,
            "explanation": "Nylon is a man-made synthetic fibre produced from chemical raw materials.",
        },
        {
            "question_text": "Which mode of heat transfer occurs through direct contact of particles?",
            "options": ["Conduction", "Convection", "Radiation", "Evaporation"],
            "correct_index": 0,
            "explanation": "Conduction transfers heat through a medium by particles passing energy to neighbouring particles.",
        },
        {
            "question_text": "Litmus paper turns red in the presence of what type of substance?",
            "options": ["A base", "An acid", "A salt", "Water"],
            "correct_index": 1,
            "explanation": "Acids turn blue litmus paper red.",
        },
        {
            "question_text": "Rusting of iron is an example of which type of change?",
            "options": ["Physical change", "Chemical change", "Reversible change", "No change"],
            "correct_index": 1,
            "explanation": "Rusting forms a new substance, iron oxide, making it a chemical change.",
        },
        {
            "question_text": "Which factor does NOT usually influence the weather of a place?",
            "options": ["Temperature", "Humidity", "Rainfall", "Population density"],
            "correct_index": 3,
            "explanation": "Weather is determined by atmospheric conditions like temperature, humidity, and rainfall, not population.",
        },
        {
            "question_text": "A tropical cyclone is also known as what in the Indian region?",
            "options": ["Typhoon", "Hurricane", "Willy-willy", "Cyclone"],
            "correct_index": 3,
            "explanation": "In the Indian Ocean region, tropical storms are called cyclones.",
        },
        {
            "question_text": "Which layer of soil is richest in humus and most fertile?",
            "options": ["Topsoil", "Subsoil", "Bedrock", "Substratum"],
            "correct_index": 0,
            "explanation": "Topsoil contains the most organic humus, making it the most fertile layer.",
        },
        {
            "question_text": "Which organ is primarily responsible for gas exchange in humans?",
            "options": ["Heart", "Lungs", "Liver", "Kidney"],
            "correct_index": 1,
            "explanation": "The lungs are the primary organs for taking in oxygen and expelling carbon dioxide.",
        },
        {
            "question_text": "Which vascular tissue transports water and minerals in plants?",
            "options": ["Phloem", "Xylem", "Cambium", "Cortex"],
            "correct_index": 1,
            "explanation": "Xylem tissue conducts water and dissolved minerals from roots to the rest of the plant.",
        },
        {
            "question_text": "The transfer of pollen from anther to stigma of the same flower is called:",
            "options": ["Cross-pollination", "Self-pollination", "Fertilization", "Germination"],
            "correct_index": 1,
            "explanation": "Self-pollination occurs when pollen moves within the same flower or plant.",
        },
        {
            "question_text": "What device is used to measure the speed of a vehicle?",
            "options": ["Odometer", "Speedometer", "Thermometer", "Barometer"],
            "correct_index": 1,
            "explanation": "A speedometer directly displays the speed of a moving vehicle.",
        },
        {
            "question_text": "What is the heating effect of electric current used in?",
            "options": ["Electric bulb only", "Electric iron and heater", "Electric bell only", "Compass"],
            "correct_index": 1,
            "explanation": "Appliances like an electric iron and heater work using the heating effect of current flowing through a resistive element.",
        },
        {
            "question_text": "Which of these materials is a good conductor of electricity?",
            "options": ["Rubber", "Plastic", "Copper", "Wood"],
            "correct_index": 2,
            "explanation": "Copper is a metal and allows electric current to pass through it easily.",
        },
        {
            "question_text": "What type of image is formed by a plane mirror?",
            "options": ["Real and inverted", "Virtual and erect", "Real and erect", "Virtual and inverted"],
            "correct_index": 1,
            "explanation": "A plane mirror always forms a virtual, erect image of the same size as the object.",
        },
        {
            "question_text": "Which of these is the main cause of water scarcity in growing cities?",
            "options": ["Too much rainfall", "Overexploitation and rising demand", "Excess groundwater", "Cold climate"],
            "correct_index": 1,
            "explanation": "Rapid population growth and overuse increase demand faster than water sources can replenish.",
        },
        {
            "question_text": "Which of the following is an example of a coniferous forest tree?",
            "options": ["Banyan", "Pine", "Mango", "Teak"],
            "correct_index": 1,
            "explanation": "Pine is a coniferous tree typically found in cooler climates.",
        },
        {
            "question_text": "Which acid is commonly found in vinegar?",
            "options": ["Citric acid", "Acetic acid", "Lactic acid", "Tartaric acid"],
            "correct_index": 1,
            "explanation": "Vinegar contains acetic acid, which gives it a sour taste.",
        },
        {
            "question_text": "A change that can be reversed, like melting of wax, is called a:",
            "options": ["Chemical change", "Reversible change", "Irreversible change", "Slow change"],
            "correct_index": 1,
            "explanation": "Melting wax can be re-solidified by cooling, so it is a reversible physical change.",
        },
        {
            "question_text": "Which gas do plants absorb from the atmosphere for photosynthesis?",
            "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
            "correct_index": 2,
            "explanation": "Plants take in carbon dioxide from the air to use in photosynthesis.",
        },
    ],
    "English": [
        {
            "question_text": "Choose the correctly punctuated sentence.",
            "options": [
                "She asked, \"where is my book?\"",
                "She asked, \"Where is my book?\"",
                "she asked, \"Where is my book\"",
                "She asked \"Where is my book?\"",
            ],
            "correct_index": 1,
            "explanation": "The quoted question starts with a capital letter and ends with a question mark inside the quotation marks.",
        },
        {
            "question_text": "Identify the tense: \"They had finished the project before the deadline.\"",
            "options": ["Simple past", "Past continuous", "Past perfect", "Present perfect"],
            "correct_index": 2,
            "explanation": "\"Had finished\" shows an action completed before another past action, which is past perfect tense.",
        },
        {
            "question_text": "Choose the correct passive voice of: \"The chef cooks the meal.\"",
            "options": [
                "The meal cooked the chef.",
                "The meal is cooked by the chef.",
                "The meal was cooked by the chef.",
                "The meal is cooking by the chef.",
            ],
            "correct_index": 1,
            "explanation": "Present simple active becomes \"is/are + past participle + by\" in passive voice.",
        },
        {
            "question_text": "Which word is a conjunction in this sentence: \"I wanted to go, but it started raining.\"",
            "options": ["wanted", "but", "started", "raining"],
            "correct_index": 1,
            "explanation": "\"But\" joins the two clauses, functioning as a conjunction.",
        },
        {
            "question_text": "Choose the correct determiner: \"___ apple a day keeps the doctor away.\"",
            "options": ["A", "An", "The", "Some"],
            "correct_index": 1,
            "explanation": "\"Apple\" begins with a vowel sound, so the article \"an\" is used.",
        },
        {
            "question_text": "Report this in indirect speech: He said, \"I am tired.\"",
            "options": [
                "He said that I am tired.",
                "He said that he was tired.",
                "He says that he is tired.",
                "He said that he is tired.",
            ],
            "correct_index": 1,
            "explanation": "In reported speech, the pronoun and tense shift back: \"am\" becomes \"was\" and \"I\" becomes \"he\".",
        },
        {
            "question_text": "Which sentence uses the correct subject-verb agreement?",
            "options": [
                "The team of players are ready.",
                "The team of players is ready.",
                "The team of players were ready.",
                "The team of players be ready.",
            ],
            "correct_index": 1,
            "explanation": "\"Team\" is a singular collective noun, so it takes the singular verb \"is\".",
        },
        {
            "question_text": "What is the antonym of \"generous\"?",
            "options": ["Kind", "Stingy", "Wealthy", "Polite"],
            "correct_index": 1,
            "explanation": "\"Stingy\" means unwilling to give, the opposite of generous.",
        },
        {
            "question_text": "What is the synonym of \"enormous\"?",
            "options": ["Tiny", "Huge", "Narrow", "Slow"],
            "correct_index": 1,
            "explanation": "\"Huge\" means very large, matching the meaning of \"enormous\".",
        },
        {
            "question_text": "Choose the correctly spelled word.",
            "options": ["Recieve", "Receive", "Receeve", "Receve"],
            "correct_index": 1,
            "explanation": "The correct spelling follows the \"i before e except after c\" rule: r-e-c-e-i-v-e.",
        },
        {
            "question_text": "Identify the clause type: \"Although it rained, we went outside.\"",
            "options": ["Main clause", "Subordinate clause", "Noun clause", "Independent clause"],
            "correct_index": 1,
            "explanation": "\"Although it rained\" cannot stand alone and depends on the main clause, making it subordinate.",
        },
        {
            "question_text": "Which is the correct plural of \"child\"?",
            "options": ["Childs", "Childes", "Children", "Childrens"],
            "correct_index": 2,
            "explanation": "\"Child\" has the irregular plural form \"children\".",
        },
        {
            "question_text": "Choose the sentence with correct preposition usage.",
            "options": [
                "She is good in maths.",
                "She is good at maths.",
                "She is good on maths.",
                "She is good for maths.",
            ],
            "correct_index": 1,
            "explanation": "The idiomatic preposition used with \"good\" for a skill is \"at\".",
        },
        {
            "question_text": "Which word is an adverb in: \"He ran quickly to the station.\"",
            "options": ["ran", "quickly", "station", "to"],
            "correct_index": 1,
            "explanation": "\"Quickly\" describes how he ran, functioning as an adverb.",
        },
        {
            "question_text": "Choose the correct comparative form of \"good\".",
            "options": ["Gooder", "More good", "Better", "Best"],
            "correct_index": 2,
            "explanation": "\"Good\" has the irregular comparative form \"better\".",
        },
        {
            "question_text": "Which sentence is in the present continuous tense?",
            "options": [
                "She writes a letter.",
                "She wrote a letter.",
                "She is writing a letter.",
                "She has written a letter.",
            ],
            "correct_index": 2,
            "explanation": "\"Is writing\" shows an action happening right now, the present continuous tense.",
        },
        {
            "question_text": "Choose the correctly formed question tag: \"You like tea, ___?\"",
            "options": ["do you", "don't you", "isn't it", "aren't you"],
            "correct_index": 1,
            "explanation": "A positive statement takes a negative question tag: \"don't you\".",
        },
        {
            "question_text": "Which word means the same as \"assist\"?",
            "options": ["Ignore", "Help", "Block", "Delay"],
            "correct_index": 1,
            "explanation": "\"Assist\" means to help someone.",
        },
        {
            "question_text": "Identify the correctly capitalised sentence.",
            "options": [
                "we visited the taj mahal in Agra.",
                "We visited the Taj Mahal in agra.",
                "We visited the Taj Mahal in Agra.",
                "We Visited the taj Mahal in Agra.",
            ],
            "correct_index": 2,
            "explanation": "Sentence beginnings and proper nouns (Taj Mahal, Agra) must be capitalised.",
        },
        {
            "question_text": "Choose the correct sentence using \"neither...nor\".",
            "options": [
                "Neither Raj nor his friends is coming.",
                "Neither Raj nor his friends are coming.",
                "Neither Raj or his friends are coming.",
                "Neither Raj nor his friends coming.",
            ],
            "correct_index": 1,
            "explanation": "With \"neither...nor\", the verb agrees with the noun closest to it, here the plural \"friends\", so \"are\" is used.",
        },
    ],
    "Hindi": [
        {
            "question_text": "\"सुंदर\" शब्द किस भेद के अंतर्गत आता है?",
            "options": ["संज्ञा", "सर्वनाम", "विशेषण", "क्रिया"],
            "correct_index": 2,
            "explanation": "\"सुंदर\" किसी संज्ञा की विशेषता बताता है, इसलिए यह विशेषण है।",
        },
        {
            "question_text": "\"वह पुस्तक पढ़ रहा है\" वाक्य में \"वह\" कौन सा शब्द भेद है?",
            "options": ["संज्ञा", "सर्वनाम", "क्रिया विशेषण", "समुच्चयबोधक"],
            "correct_index": 1,
            "explanation": "\"वह\" संज्ञा के स्थान पर प्रयोग होता है, इसलिए यह सर्वनाम है।",
        },
        {
            "question_text": "\"राम + ईश्वर\" के संधि-विच्छेद से बना शब्द क्या है?",
            "options": ["रामेश्वर", "रामईश्वर", "रामश्वर", "रामेस्वर"],
            "correct_index": 0,
            "explanation": "अ + ई = ए स्वर संधि के नियम से राम + ईश्वर = रामेश्वर बनता है।",
        },
        {
            "question_text": "\"पंचवटी\" शब्द किस समास का उदाहरण है?",
            "options": ["तत्पुरुष समास", "द्विगु समास", "द्वंद्व समास", "बहुव्रीहि समास"],
            "correct_index": 1,
            "explanation": "संख्यावाचक शब्द से बने समास को द्विगु समास कहते हैं; \"पंचवटी\" का अर्थ है पाँच वटों का समूह।",
        },
        {
            "question_text": "\"आँखों में धूल झोंकना\" मुहावरे का सही अर्थ क्या है?",
            "options": ["धोखा देना", "मदद करना", "क्रोध करना", "प्रशंसा करना"],
            "correct_index": 0,
            "explanation": "इस मुहावरे का अर्थ है किसी को धोखे में रखना या भ्रमित करना।",
        },
        {
            "question_text": "\"राम ने रोटी खाई\" वाक्य में कर्ता का कारक चिह्न क्या है?",
            "options": ["को", "ने", "से", "में"],
            "correct_index": 1,
            "explanation": "इस वाक्य में कर्ता कारक का चिह्न \"ने\" है, जो भूतकाल की सकर्मक क्रिया के साथ प्रयोग होता है।",
        },
        {
            "question_text": "\"वह कल विद्यालय जाएगा\" वाक्य किस काल में है?",
            "options": ["वर्तमान काल", "भूतकाल", "भविष्य काल", "अपूर्ण काल"],
            "correct_index": 2,
            "explanation": "\"जाएगा\" क्रिया भविष्य में होने वाली क्रिया को दर्शाती है, इसलिए यह भविष्य काल है।",
        },
        {
            "question_text": "\"पुस्तक पढ़ी जाती है\" वाक्य किस वाच्य का उदाहरण है?",
            "options": ["कर्तृवाच्य", "कर्मवाच्य", "भाववाच्य", "इनमें से कोई नहीं"],
            "correct_index": 1,
            "explanation": "जब क्रिया का बल कर्म पर हो और कर्ता गौण हो, तो वह कर्मवाच्य कहलाता है।",
        },
        {
            "question_text": "\"बड़ा\" शब्द का विलोम शब्द क्या है?",
            "options": ["ऊँचा", "छोटा", "लंबा", "गहरा"],
            "correct_index": 1,
            "explanation": "\"बड़ा\" का विलोम शब्द \"छोटा\" होता है।",
        },
        {
            "question_text": "\"सूर्य\" शब्द का पर्यायवाची शब्द कौन सा है?",
            "options": ["चंद्रमा", "दिनकर", "तारा", "आकाश"],
            "correct_index": 1,
            "explanation": "\"दिनकर\" सूर्य का ही एक पर्यायवाची शब्द है।",
        },
        {
            "question_text": "\"बालक\" शब्द का स्त्रीलिंग रूप क्या है?",
            "options": ["बालिका", "बालकी", "बालकिन", "बालकनी"],
            "correct_index": 0,
            "explanation": "\"बालक\" का स्त्रीलिंग रूप \"बालिका\" है।",
        },
        {
            "question_text": "\"पुस्तकें\" शब्द में कौन सा वचन है?",
            "options": ["एकवचन", "बहुवचन", "उभयवचन", "कोई नहीं"],
            "correct_index": 1,
            "explanation": "\"पुस्तकें\" एक से अधिक वस्तुओं को दर्शाता है, इसलिए यह बहुवचन है।",
        },
        {
            "question_text": "\"दौड़ना\" शब्द किस भेद से संबंधित है?",
            "options": ["संज्ञा", "सर्वनाम", "क्रिया", "विशेषण"],
            "correct_index": 2,
            "explanation": "\"दौड़ना\" किसी कार्य के होने का बोध कराता है, इसलिए यह क्रिया है।",
        },
        {
            "question_text": "\"राजा और रानी\" में कौन सा समास है?",
            "options": ["तत्पुरुष समास", "कर्मधारय समास", "द्वंद्व समास", "अव्ययीभाव समास"],
            "correct_index": 2,
            "explanation": "दोनों पदों के बीच \"और\" का लोप होकर बना समास द्वंद्व समास कहलाता है।",
        },
        {
            "question_text": "\"नाक कटना\" मुहावरे का सही अर्थ क्या है?",
            "options": ["प्रसन्न होना", "अपमानित होना", "बीमार होना", "सो जाना"],
            "correct_index": 1,
            "explanation": "\"नाक कटना\" का अर्थ है इज्जत या प्रतिष्ठा का नाश होना।",
        },
        {
            "question_text": "\"मोहन को पत्र लिखना है\" वाक्य में \"को\" किस कारक का चिह्न है?",
            "options": ["कर्ता कारक", "कर्म कारक", "करण कारक", "संप्रदान कारक"],
            "correct_index": 3,
            "explanation": "जिसके लिए क्रिया की जाए उसे संप्रदान कारक कहते हैं, जिसका चिह्न \"को\" है।",
        },
        {
            "question_text": "\"वह पढ़ता है\" का भूतकाल रूप क्या है?",
            "options": ["वह पढ़ेगा", "वह पढ़ता था", "वह पढ़ रहा है", "वह पढ़ चुका होगा"],
            "correct_index": 1,
            "explanation": "\"पढ़ता था\" भूतकाल में नियमित रूप से होने वाली क्रिया को दर्शाता है।",
        },
        {
            "question_text": "\"अच्छा\" शब्द का विलोम शब्द क्या है?",
            "options": ["सुंदर", "बुरा", "स्वच्छ", "मीठा"],
            "correct_index": 1,
            "explanation": "\"अच्छा\" का विलोम शब्द \"बुरा\" होता है।",
        },
        {
            "question_text": "\"जल\" शब्द का पर्यायवाची शब्द कौन सा है?",
            "options": ["अग्नि", "नीर", "वायु", "धरती"],
            "correct_index": 1,
            "explanation": "\"नीर\" जल का ही एक पर्यायवाची शब्द है।",
        },
        {
            "question_text": "\"लड़का दौड़ रहा है\" वाक्य में क्रिया का कौन सा रूप प्रयुक्त हुआ है?",
            "options": ["सामान्य वर्तमान", "पूर्ण वर्तमान", "अपूर्ण वर्तमान", "संदिग्ध वर्तमान"],
            "correct_index": 2,
            "explanation": "\"दौड़ रहा है\" क्रिया के जारी रहने को दर्शाती है, यह अपूर्ण वर्तमान (वर्तमान सातत्यबोधक) है।",
        },
    ],
    "Social Science": [
        {
            "question_text": "Who founded the Delhi Sultanate in 1206 CE?",
            "options": ["Muhammad Ghori", "Qutb-ud-din Aibak", "Iltutmish", "Balban"],
            "correct_index": 1,
            "explanation": "Qutb-ud-din Aibak, a former general, established the Delhi Sultanate in 1206 CE.",
        },
        {
            "question_text": "Which Mughal emperor built the Taj Mahal?",
            "options": ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"],
            "correct_index": 2,
            "explanation": "Shah Jahan commissioned the Taj Mahal in memory of his wife Mumtaz Mahal.",
        },
        {
            "question_text": "Which dynasty is known for administrative reforms including the Mansabdari system?",
            "options": ["Delhi Sultanate", "Mughal dynasty", "Maratha empire", "Vijayanagara empire"],
            "correct_index": 1,
            "explanation": "The Mansabdari system, ranking officials by military and civil duties, was introduced under the Mughals.",
        },
        {
            "question_text": "Which layer of the earth is the outermost and thinnest?",
            "options": ["Core", "Mantle", "Crust", "Lithosphere only"],
            "correct_index": 2,
            "explanation": "The crust is the thin, outermost solid layer on which we live.",
        },
        {
            "question_text": "What is the process by which rocks break down into smaller particles called?",
            "options": ["Erosion", "Weathering", "Deposition", "Transportation"],
            "correct_index": 1,
            "explanation": "Weathering is the breaking down of rocks by natural agents like wind, water, and temperature changes.",
        },
        {
            "question_text": "Which gas makes up the largest percentage of the Earth's atmosphere?",
            "options": ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"],
            "correct_index": 2,
            "explanation": "Nitrogen makes up about 78% of the atmosphere, the largest share of any gas.",
        },
        {
            "question_text": "Which of the following is an example of natural vegetation found in tropical regions?",
            "options": ["Tundra vegetation", "Tropical evergreen forest", "Coniferous forest", "Desert scrub only"],
            "correct_index": 1,
            "explanation": "Tropical evergreen forests grow in regions with heavy rainfall and high temperatures, like India's Western Ghats.",
        },
        {
            "question_text": "What is the water cycle process where water vapour turns into liquid water called?",
            "options": ["Evaporation", "Condensation", "Precipitation", "Transpiration"],
            "correct_index": 1,
            "explanation": "Condensation is the process by which water vapour cools and changes into liquid droplets.",
        },
        {
            "question_text": "Equality in a democracy primarily means what?",
            "options": [
                "Everyone has the same income",
                "Everyone is treated with equal dignity and rights",
                "Everyone holds the same job",
                "Everyone follows the same religion",
            ],
            "correct_index": 1,
            "explanation": "Equality in a democratic society refers to equal rights, dignity, and treatment for all citizens under the law.",
        },
        {
            "question_text": "Which level of government is primarily responsible for subjects like police and public health in India?",
            "options": ["Central government only", "State government", "Local panchayat only", "United Nations"],
            "correct_index": 1,
            "explanation": "Police and public health fall under the State List, making state governments primarily responsible.",
        },
        {
            "question_text": "What is the primary role of media in a democracy?",
            "options": ["To only entertain", "To inform citizens and hold power accountable", "To sell products", "To govern the country"],
            "correct_index": 1,
            "explanation": "Media informs the public about events and policies and questions those in power, supporting democratic accountability.",
        },
        {
            "question_text": "A market where goods are bought and sold in small quantities directly to consumers is called:",
            "options": ["Wholesale market", "Retail market", "Weekly market only", "Stock market"],
            "correct_index": 1,
            "explanation": "A retail market sells goods directly to final consumers, often in smaller quantities.",
        },
        {
            "question_text": "Which ruler of the Delhi Sultanate is known for introducing token currency?",
            "options": ["Alauddin Khalji", "Muhammad bin Tughlaq", "Balban", "Iltutmish"],
            "correct_index": 1,
            "explanation": "Muhammad bin Tughlaq introduced token currency made of base metal during his reign.",
        },
        {
            "question_text": "Which Mughal ruler is known for his policy of religious tolerance, including abolishing the jizya tax?",
            "options": ["Babur", "Akbar", "Aurangzeb", "Humayun"],
            "correct_index": 1,
            "explanation": "Akbar pursued a policy of religious tolerance and abolished the jizya tax on non-Muslims.",
        },
        {
            "question_text": "Which of these best describes an igneous rock?",
            "options": [
                "Formed from cooling and solidifying magma or lava",
                "Formed from layers of sediment",
                "Formed under heat and pressure from existing rocks",
                "Formed only from plant and animal remains",
            ],
            "correct_index": 0,
            "explanation": "Igneous rocks form when molten magma or lava cools and solidifies.",
        },
        {
            "question_text": "Which of the following is a renewable natural resource?",
            "options": ["Coal", "Natural gas", "Forest", "Petroleum"],
            "correct_index": 2,
            "explanation": "Forests can regenerate over time through growth and replanting, making them a renewable resource.",
        },
        {
            "question_text": "Winds blowing from a high pressure area to a low pressure area are influenced mainly by differences in:",
            "options": ["Air pressure", "Ocean colour", "Soil type", "Population"],
            "correct_index": 0,
            "explanation": "Wind is caused by air moving from areas of high pressure to areas of low pressure.",
        },
        {
            "question_text": "What does the term 'diversity' mean in the context of Indian society?",
            "options": [
                "Everyone being identical",
                "The presence of different cultures, religions, and languages coexisting",
                "A single dominant culture",
                "The absence of any differences",
            ],
            "correct_index": 1,
            "explanation": "Diversity refers to the coexistence of many different cultures, languages, and religions within one society.",
        },
        {
            "question_text": "Which of the following best defines a democratic government?",
            "options": [
                "Rule by a single king",
                "Rule by the military",
                "A government elected by the people",
                "Rule by foreign powers",
            ],
            "correct_index": 2,
            "explanation": "A democratic government is one chosen through free elections by the people it governs.",
        },
        {
            "question_text": "Which of the following best describes a weekly market?",
            "options": [
                "A permanent large shopping mall",
                "A market held on a fixed day at a particular place each week",
                "An online-only marketplace",
                "A market that sells only wholesale goods",
            ],
            "correct_index": 1,
            "explanation": "A weekly market sets up at a fixed location on a specific day each week, common in villages and towns.",
        },
    ],
}
