QUESTIONS: dict[str, list[dict]] = {
    "Physics": [
        {
            "question_text": "What is the SI unit of force?",
            "options": ["Newton", "Joule", "Watt", "Pascal"],
            "correct_index": 0,
            "explanation": "Force equals mass times acceleration, and its SI unit is the newton (kg·m/s²).",
        },
        {
            "question_text": "What is the dimensional formula of force?",
            "options": ["[MLT^-2]", "[ML^2T^-2]", "[MLT^-1]", "[ML^-1T^-2]"],
            "correct_index": 0,
            "explanation": "Force = mass × acceleration, giving dimensions of mass × length × time^-2.",
        },
        {
            "question_text": "A body moving with constant velocity has an acceleration equal to:",
            "options": ["Zero", "A constant non-zero value", "An increasing value", "A decreasing value"],
            "correct_index": 0,
            "explanation": "Constant velocity means no change in speed or direction, so acceleration is zero.",
        },
        {
            "question_text": "Newton's first law of motion is also known as the:",
            "options": ["Law of inertia", "Law of momentum", "Law of action-reaction", "Law of gravitation"],
            "correct_index": 0,
            "explanation": "Newton's first law describes a body's tendency to resist changes in motion, called inertia.",
        },
        {
            "question_text": "What is the SI unit of momentum?",
            "options": ["kg·m/s", "kg·m/s^2", "Newton", "Joule"],
            "correct_index": 0,
            "explanation": "Momentum is mass times velocity, so its unit is kg·m/s.",
        },
        {
            "question_text": "Newton's third law states that for every action there is:",
            "options": [
                "An equal and opposite reaction",
                "A smaller opposite reaction",
                "No reaction at all",
                "A reaction in the same direction",
            ],
            "correct_index": 0,
            "explanation": "Newton's third law states action and reaction forces are equal in magnitude and opposite in direction.",
        },
        {
            "question_text": "The work done by a force F over a displacement d is given by:",
            "options": ["W = F·d·cos(θ)", "W = F·d·sin(θ)", "W = F + d", "W = F/d"],
            "correct_index": 0,
            "explanation": "Work is the dot product of force and displacement, W = F·d·cos(θ), where θ is the angle between them.",
        },
        {
            "question_text": "The kinetic energy of a body of mass m moving with velocity v is:",
            "options": ["(1/2)mv^2", "mv^2", "mv", "(1/2)mv"],
            "correct_index": 0,
            "explanation": "Kinetic energy is defined as one-half the mass times the square of velocity.",
        },
        {
            "question_text": "Power is defined as the rate of doing:",
            "options": ["Work", "Force", "Momentum", "Displacement"],
            "correct_index": 0,
            "explanation": "Power is the amount of work done per unit time.",
        },
        {
            "question_text": "The center of mass of a uniform rod lies at:",
            "options": ["Its geometric midpoint", "One end", "The other end", "A point outside the rod"],
            "correct_index": 0,
            "explanation": "For a uniform rod, mass is evenly distributed, so the center of mass is at the midpoint.",
        },
        {
            "question_text": "The moment of inertia of a body depends on its:",
            "options": [
                "Mass and its distribution about the axis of rotation",
                "Mass only",
                "Shape only, regardless of mass",
                "Velocity only",
            ],
            "correct_index": 0,
            "explanation": "Moment of inertia depends on both the mass of the body and how that mass is distributed relative to the rotation axis.",
        },
        {
            "question_text": "The universal law of gravitation was proposed by:",
            "options": ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Albert Einstein"],
            "correct_index": 0,
            "explanation": "Isaac Newton formulated the universal law of gravitation in the 17th century.",
        },
        {
            "question_text": "The escape velocity from Earth's surface is approximately:",
            "options": ["11.2 km/s", "7.9 km/s", "3.6 km/s", "25 km/s"],
            "correct_index": 0,
            "explanation": "Earth's escape velocity, the minimum speed to break free of its gravity, is about 11.2 km/s.",
        },
        {
            "question_text": "The SI unit of stress is the same as the SI unit of:",
            "options": ["Pressure", "Force", "Energy", "Power"],
            "correct_index": 0,
            "explanation": "Stress is force per unit area, measured in pascals, the same unit as pressure.",
        },
        {
            "question_text": "Hooke's law states that, within the elastic limit, stress is directly proportional to:",
            "options": ["Strain", "Force", "Volume", "Temperature"],
            "correct_index": 0,
            "explanation": "Hooke's law states stress is proportional to strain within the elastic limit of a material.",
        },
        {
            "question_text": "The SI unit of pressure is the:",
            "options": ["Pascal", "Newton", "Joule", "Watt"],
            "correct_index": 0,
            "explanation": "Pressure is force per unit area, and its SI unit is the pascal (N/m^2).",
        },
        {
            "question_text": "The zeroth law of thermodynamics is related to the concept of:",
            "options": ["Thermal equilibrium", "Conservation of energy", "Entropy increase", "Heat engine efficiency"],
            "correct_index": 0,
            "explanation": "The zeroth law establishes the idea of temperature via systems in thermal equilibrium with each other.",
        },
        {
            "question_text": "In an adiabatic process, there is no exchange of ___ between the system and surroundings.",
            "options": ["Heat", "Work", "Volume", "Pressure"],
            "correct_index": 0,
            "explanation": "An adiabatic process is defined as one in which no heat enters or leaves the system.",
        },
        {
            "question_text": "The time period of a simple pendulum depends on its:",
            "options": [
                "Length and the acceleration due to gravity",
                "Mass of the bob only",
                "Amplitude of swing only",
                "Color of the bob",
            ],
            "correct_index": 0,
            "explanation": "For small oscillations, T = 2π√(l/g), so time period depends on length l and gravity g, not mass or amplitude.",
        },
        {
            "question_text": "The speed of sound is generally greatest in:",
            "options": ["Solids", "Liquids", "Gases", "Vacuum"],
            "correct_index": 0,
            "explanation": "Sound travels fastest through solids because their particles are most closely packed, allowing faster transmission of vibrations.",
        },
    ],
    "Chemistry": [
        {
            "question_text": "One mole of any substance contains how many elementary particles?",
            "options": ["6.022 × 10^23", "6.022 × 10^22", "3.011 × 10^23", "1.66 × 10^-24"],
            "correct_index": 0,
            "explanation": "This is Avogadro's number, the number of particles in one mole of a substance.",
        },
        {
            "question_text": "Which subatomic particles are found in the nucleus of an atom?",
            "options": ["Protons and neutrons", "Electrons and protons", "Only electrons", "Only neutrons"],
            "correct_index": 0,
            "explanation": "The nucleus contains protons and neutrons, while electrons orbit around it.",
        },
        {
            "question_text": "Which quantum number determines the shape of an orbital?",
            "options": ["Azimuthal (l)", "Principal (n)", "Magnetic (m)", "Spin (s)"],
            "correct_index": 0,
            "explanation": "The azimuthal quantum number l determines the subshell and hence the shape of the orbital.",
        },
        {
            "question_text": "The modern periodic law states that properties of elements are a periodic function of their:",
            "options": ["Atomic number", "Atomic mass", "Number of neutrons", "Valency"],
            "correct_index": 0,
            "explanation": "Mendeleev used atomic mass, but the modern periodic law is based on atomic number.",
        },
        {
            "question_text": "A bond formed by the complete transfer of electrons from one atom to another is called:",
            "options": ["An ionic bond", "A covalent bond", "A metallic bond", "A hydrogen bond"],
            "correct_index": 0,
            "explanation": "Ionic bonds form when electrons are transferred, creating oppositely charged ions that attract each other.",
        },
        {
            "question_text": "According to VSEPR theory, the shape of a methane (CH4) molecule is:",
            "options": ["Tetrahedral", "Linear", "Trigonal planar", "Pyramidal"],
            "correct_index": 0,
            "explanation": "Methane has four bond pairs and no lone pairs on carbon, giving it a tetrahedral shape.",
        },
        {
            "question_text": "Which gas law states that at constant temperature, volume is inversely proportional to pressure?",
            "options": ["Boyle's law", "Charles's law", "Gay-Lussac's law", "Avogadro's law"],
            "correct_index": 0,
            "explanation": "Boyle's law relates volume and pressure of a fixed amount of gas at constant temperature.",
        },
        {
            "question_text": "Enthalpy change of a reaction is denoted by the symbol:",
            "options": ["ΔH", "ΔS", "ΔG", "ΔU"],
            "correct_index": 0,
            "explanation": "Enthalpy change is represented by ΔH in thermochemistry.",
        },
        {
            "question_text": "A reaction with a negative value of Gibbs free energy change (ΔG) is:",
            "options": ["Spontaneous", "Non-spontaneous", "Always at equilibrium", "Always endothermic"],
            "correct_index": 0,
            "explanation": "A negative ΔG indicates the reaction can proceed spontaneously under the given conditions.",
        },
        {
            "question_text": "Le Chatelier's principle applies to a system that is at:",
            "options": ["Equilibrium", "Absolute zero", "Standard temperature only", "Its boiling point"],
            "correct_index": 0,
            "explanation": "Le Chatelier's principle predicts how a system at equilibrium responds to a change in conditions.",
        },
        {
            "question_text": "Oxidation, in terms of electron transfer, is defined as:",
            "options": ["Loss of electrons", "Gain of electrons", "Loss of protons", "Gain of protons"],
            "correct_index": 0,
            "explanation": "Oxidation is the loss of electrons by a substance; reduction is the gain of electrons.",
        },
        {
            "question_text": "Which element has the electronic configuration 1s^1?",
            "options": ["Hydrogen", "Helium", "Lithium", "Sodium"],
            "correct_index": 0,
            "explanation": "Hydrogen has a single electron, occupying the 1s orbital, giving configuration 1s^1.",
        },
        {
            "question_text": "Alkali metals belong to which group of the periodic table?",
            "options": ["Group 1", "Group 2", "Group 17", "Group 18"],
            "correct_index": 0,
            "explanation": "Alkali metals such as lithium and sodium are placed in Group 1.",
        },
        {
            "question_text": "Which of the following is a p-block (Group 14) element?",
            "options": ["Carbon", "Sodium", "Chlorine", "Calcium"],
            "correct_index": 0,
            "explanation": "Carbon belongs to Group 14 of the p-block; sodium and calcium are s-block, chlorine is Group 17.",
        },
        {
            "question_text": "What is the IUPAC name of CH4?",
            "options": ["Methane", "Ethane", "Propane", "Butane"],
            "correct_index": 0,
            "explanation": "CH4, the simplest alkane with one carbon atom, is named methane.",
        },
        {
            "question_text": "Compounds with the same molecular formula but different structural arrangements are called:",
            "options": ["Isomers", "Isotopes", "Isobars", "Allotropes"],
            "correct_index": 0,
            "explanation": "Isomers share a molecular formula but differ in the arrangement of atoms.",
        },
        {
            "question_text": "The general formula of alkanes is:",
            "options": ["CnH2n+2", "CnH2n", "CnH2n-2", "CnHn"],
            "correct_index": 0,
            "explanation": "Alkanes are saturated hydrocarbons following the general formula CnH2n+2.",
        },
        {
            "question_text": "Which gas is evolved when zinc reacts with dilute hydrochloric acid?",
            "options": ["Hydrogen", "Oxygen", "Chlorine", "Carbon dioxide"],
            "correct_index": 0,
            "explanation": "Zinc reacts with dilute HCl to give zinc chloride and hydrogen gas.",
        },
        {
            "question_text": "The pH of a neutral aqueous solution at 25°C is:",
            "options": ["7", "0", "14", "1"],
            "correct_index": 0,
            "explanation": "Pure water at 25°C has an equal concentration of H+ and OH- ions, giving a pH of 7.",
        },
        {
            "question_text": "Which of the following reactions involves both oxidation and reduction?",
            "options": [
                "2Mg + O2 → 2MgO",
                "NaOH + HCl → NaCl + H2O",
                "Dissolving sugar in water",
                "Melting of ice",
            ],
            "correct_index": 0,
            "explanation": "Magnesium is oxidized and oxygen is reduced when magnesium burns to form magnesium oxide, making it a redox reaction.",
        },
    ],
    "Mathematics": [
        {
            "question_text": "If A = {1, 2, 3} and B = {2, 3, 4}, what is A ∩ B?",
            "options": ["{2, 3}", "{1, 2, 3, 4}", "{1}", "{4}"],
            "correct_index": 0,
            "explanation": "The intersection contains elements common to both sets, which are 2 and 3.",
        },
        {
            "question_text": "The number of elements in the power set of a set with n elements is:",
            "options": ["2^n", "n^2", "n!", "2n"],
            "correct_index": 0,
            "explanation": "A set with n elements has 2^n subsets, including the empty set and the set itself.",
        },
        {
            "question_text": "What is the value of sin(90°)?",
            "options": ["1", "0", "-1", "1/2"],
            "correct_index": 0,
            "explanation": "sin(90°) equals 1, its maximum value on the unit circle.",
        },
        {
            "question_text": "What is the value of cos(0°)?",
            "options": ["1", "0", "-1", "1/2"],
            "correct_index": 0,
            "explanation": "cos(0°) equals 1, as the adjacent side equals the hypotenuse at zero angle.",
        },
        {
            "question_text": "What is the value of i^2, where i is the imaginary unit?",
            "options": ["-1", "1", "i", "-i"],
            "correct_index": 0,
            "explanation": "By definition, the imaginary unit i satisfies i^2 = -1.",
        },
        {
            "question_text": "In how many ways can 5 distinct objects be arranged in a row?",
            "options": ["120", "20", "25", "60"],
            "correct_index": 0,
            "explanation": "The number of arrangements of 5 distinct objects is 5! = 120.",
        },
        {
            "question_text": "The number of ways of selecting 2 objects out of 5, without regard to order, is:",
            "options": ["10", "20", "5", "25"],
            "correct_index": 0,
            "explanation": "C(5,2) = 5!/(2!·3!) = 10.",
        },
        {
            "question_text": "In the binomial expansion of (a + b)^n, the total number of terms is:",
            "options": ["n + 1", "n", "n - 1", "2n"],
            "correct_index": 0,
            "explanation": "The binomial expansion of (a+b)^n has terms for powers 0 through n, giving n+1 terms total.",
        },
        {
            "question_text": "The sum of the first n natural numbers is:",
            "options": ["n(n + 1)/2", "n(n - 1)/2", "n^2", "n(n + 1)"],
            "correct_index": 0,
            "explanation": "The formula for the sum of the first n natural numbers is n(n+1)/2.",
        },
        {
            "question_text": "The nth term of an arithmetic progression with first term a and common difference d is:",
            "options": ["a + (n - 1)d", "a + nd", "a - (n - 1)d", "nd"],
            "correct_index": 0,
            "explanation": "The nth term of an AP is given by a + (n-1)d.",
        },
        {
            "question_text": "The slope of a line passing through (0, 0) and (2, 2) is:",
            "options": ["1", "2", "0", "Undefined"],
            "correct_index": 0,
            "explanation": "Slope = (y2 - y1)/(x2 - x1) = (2 - 0)/(2 - 0) = 1.",
        },
        {
            "question_text": "The equation x²/a² + y²/b² = 1 (with a ≠ b) represents which conic section?",
            "options": ["An ellipse", "A circle", "A parabola", "A hyperbola"],
            "correct_index": 0,
            "explanation": "This standard form with distinct positive denominators for x² and y² represents an ellipse.",
        },
        {
            "question_text": "The distance between the points (0, 0, 0) and (1, 1, 1) in 3D space is:",
            "options": ["√3", "3", "1", "√2"],
            "correct_index": 0,
            "explanation": "Distance = √(1² + 1² + 1²) = √3.",
        },
        {
            "question_text": "The derivative of x² with respect to x is:",
            "options": ["2x", "x", "x²", "2"],
            "correct_index": 0,
            "explanation": "Using the power rule, d/dx(x²) = 2x^(2-1) = 2x.",
        },
        {
            "question_text": "What is the value of lim(x→0) sin(x)/x?",
            "options": ["1", "0", "Infinity", "Undefined"],
            "correct_index": 0,
            "explanation": "This is a standard trigonometric limit that evaluates to 1.",
        },
        {
            "question_text": "The mean of the data set 2, 4, 6, 8, 10 is:",
            "options": ["6", "5", "8", "10"],
            "correct_index": 0,
            "explanation": "Mean = (2+4+6+8+10)/5 = 30/5 = 6.",
        },
        {
            "question_text": "Variance is a measure of:",
            "options": [
                "The spread of data around the mean",
                "The central value of the data",
                "The most frequent value",
                "The range of the data only",
            ],
            "correct_index": 0,
            "explanation": "Variance quantifies how much the data points deviate from the mean on average.",
        },
        {
            "question_text": "The probability of getting a head when a fair coin is tossed once is:",
            "options": ["1/2", "1", "0", "1/4"],
            "correct_index": 0,
            "explanation": "A fair coin has two equally likely outcomes, so the probability of heads is 1/2.",
        },
        {
            "question_text": "A relation that is reflexive, symmetric, and transitive is called:",
            "options": ["An equivalence relation", "A function", "A bijection", "An identity relation"],
            "correct_index": 0,
            "explanation": "A relation satisfying all three properties — reflexive, symmetric, and transitive — is called an equivalence relation.",
        },
        {
            "question_text": "The domain of the function f(x) = 1/x is:",
            "options": [
                "All real numbers except 0",
                "All real numbers",
                "Only positive numbers",
                "Only negative numbers",
            ],
            "correct_index": 0,
            "explanation": "f(x) = 1/x is undefined at x = 0, so the domain excludes zero.",
        },
    ],
    "Biology": [
        {
            "question_text": "The five kingdom classification of living organisms was proposed by:",
            "options": ["R.H. Whittaker", "Carl Linnaeus", "Charles Darwin", "Robert Hooke"],
            "correct_index": 0,
            "explanation": "R.H. Whittaker proposed the five kingdom classification system in 1969.",
        },
        {
            "question_text": "Which kingdom consists of prokaryotic organisms?",
            "options": ["Monera", "Protista", "Fungi", "Plantae"],
            "correct_index": 0,
            "explanation": "Kingdom Monera includes bacteria and other organisms lacking a true nucleus.",
        },
        {
            "question_text": "The basic unit of biological classification is the:",
            "options": ["Species", "Genus", "Family", "Order"],
            "correct_index": 0,
            "explanation": "Species is the most fundamental and specific rank in taxonomic classification.",
        },
        {
            "question_text": "The cell wall of plant cells is mainly composed of:",
            "options": ["Cellulose", "Chitin", "Peptidoglycan", "Protein"],
            "correct_index": 0,
            "explanation": "Plant cell walls are primarily made of cellulose, unlike fungal walls (chitin) or bacterial walls (peptidoglycan).",
        },
        {
            "question_text": "Which cell organelle is known as the powerhouse of the cell?",
            "options": ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"],
            "correct_index": 0,
            "explanation": "Mitochondria generate ATP through cellular respiration, earning them this nickname.",
        },
        {
            "question_text": "DNA and RNA belong to which class of biomolecules?",
            "options": ["Nucleic acids", "Proteins", "Carbohydrates", "Lipids"],
            "correct_index": 0,
            "explanation": "DNA and RNA are nucleic acids, made of nucleotide monomers.",
        },
        {
            "question_text": "The process by which green plants make their own food using sunlight is called:",
            "options": ["Photosynthesis", "Respiration", "Transpiration", "Digestion"],
            "correct_index": 0,
            "explanation": "Photosynthesis converts light energy into chemical energy stored in glucose.",
        },
        {
            "question_text": "The green pigment in plants that absorbs sunlight for photosynthesis is:",
            "options": ["Chlorophyll", "Carotene", "Xanthophyll", "Anthocyanin"],
            "correct_index": 0,
            "explanation": "Chlorophyll is the primary pigment that captures light energy for photosynthesis.",
        },
        {
            "question_text": "Exchange of gases in plant leaves occurs mainly through:",
            "options": ["Stomata", "Roots", "Xylem", "Phloem"],
            "correct_index": 0,
            "explanation": "Stomata are tiny pores on leaf surfaces that regulate gas exchange.",
        },
        {
            "question_text": "Water and dissolved minerals are transported upward in plants through the:",
            "options": ["Xylem", "Phloem", "Cambium", "Cortex"],
            "correct_index": 0,
            "explanation": "Xylem tissue conducts water and minerals from roots to the rest of the plant.",
        },
        {
            "question_text": "Food (organic nutrients) produced by photosynthesis is transported through the:",
            "options": ["Phloem", "Xylem", "Epidermis", "Cuticle"],
            "correct_index": 0,
            "explanation": "Phloem transports the products of photosynthesis, mainly sucrose, throughout the plant.",
        },
        {
            "question_text": "The functional and structural unit of the kidney is called the:",
            "options": ["Nephron", "Neuron", "Alveolus", "Nephridium"],
            "correct_index": 0,
            "explanation": "Each kidney contains millions of nephrons, which filter blood and form urine.",
        },
        {
            "question_text": "The basic functional unit of the nervous system is the:",
            "options": ["Neuron", "Nephron", "Axon", "Synapse"],
            "correct_index": 0,
            "explanation": "Neurons are specialized cells that transmit electrical and chemical signals in the nervous system.",
        },
        {
            "question_text": "In humans, the exchange of gases during breathing occurs in the:",
            "options": ["Alveoli of the lungs", "Trachea", "Bronchi", "Nasal cavity"],
            "correct_index": 0,
            "explanation": "Alveoli are tiny air sacs where oxygen and carbon dioxide are exchanged with the blood.",
        },
        {
            "question_text": "The fluid, non-cellular part of blood is called:",
            "options": ["Plasma", "Serum", "Lymph", "Platelets"],
            "correct_index": 0,
            "explanation": "Plasma is the liquid component of blood that carries cells, nutrients, and proteins.",
        },
        {
            "question_text": "The hormone that regulates blood sugar levels and is secreted by the pancreas is:",
            "options": ["Insulin", "Thyroxine", "Adrenaline", "Estrogen"],
            "correct_index": 0,
            "explanation": "Insulin, secreted by the pancreas, lowers blood glucose levels.",
        },
        {
            "question_text": "DNA replication occurs during which phase of the cell cycle?",
            "options": ["S phase", "G1 phase", "G2 phase", "M phase"],
            "correct_index": 0,
            "explanation": "The S (synthesis) phase is when the cell duplicates its DNA before division.",
        },
        {
            "question_text": "Locomotion in humans is primarily achieved by the coordinated action of:",
            "options": ["Muscles and bones", "Nerves alone", "Blood vessels", "Skin"],
            "correct_index": 0,
            "explanation": "The musculoskeletal system, muscles working with bones, enables body movement.",
        },
        {
            "question_text": "The process of taking in oxygen-rich air and expelling carbon dioxide-rich air is called:",
            "options": ["Breathing", "Photosynthesis", "Excretion", "Digestion"],
            "correct_index": 0,
            "explanation": "Breathing (external respiration) is the mechanical process of inhaling and exhaling air.",
        },
        {
            "question_text": "Auxins are an example of:",
            "options": ["Plant growth hormones", "Animal hormones", "Digestive enzymes", "Vitamins"],
            "correct_index": 0,
            "explanation": "Auxins regulate plant growth processes such as cell elongation and tropisms.",
        },
    ],
    "English": [
        {
            "question_text": "Choose the correct passive voice of: 'She writes a letter.'",
            "options": [
                "A letter is written by her.",
                "A letter was written by her.",
                "A letter is being written by her.",
                "A letter has written by her.",
            ],
            "correct_index": 0,
            "explanation": "Present simple active becomes present simple passive: 'is written by'.",
        },
        {
            "question_text": "Choose the correctly punctuated sentence.",
            "options": [
                "Although it was raining, we went out.",
                "Although it was raining we went out",
                "although it was raining, we went out.",
                "Although, it was raining we went out.",
            ],
            "correct_index": 0,
            "explanation": "An introductory subordinate clause is followed by a comma, and the sentence must start with a capital letter and end with a full stop.",
        },
        {
            "question_text": "Choose the correct reported speech of: He said, 'I am going home.'",
            "options": [
                "He said that he was going home.",
                "He said that he is going home.",
                "He said he go home.",
                "He told that I am going home.",
            ],
            "correct_index": 0,
            "explanation": "In reported speech, present continuous ('am going') shifts back to past continuous ('was going'), and the pronoun changes to 'he'.",
        },
        {
            "question_text": "Fill in the blank: 'Neither of the boys ___ present.'",
            "options": ["was", "were", "are", "have been"],
            "correct_index": 0,
            "explanation": "'Neither' takes a singular verb, so 'was' is correct.",
        },
        {
            "question_text": "Choose the word closest in meaning to 'Abundant'.",
            "options": ["Plentiful", "Scarce", "Empty", "Rare"],
            "correct_index": 0,
            "explanation": "'Abundant' means existing in large quantities, which is closest to 'plentiful'.",
        },
        {
            "question_text": "Choose the antonym of 'Ancient'.",
            "options": ["Modern", "Old", "Antique", "Historic"],
            "correct_index": 0,
            "explanation": "'Modern' means belonging to the present, the opposite of 'ancient'.",
        },
        {
            "question_text": "Identify the grammatically correct sentence.",
            "options": [
                "She don't like coffee.",
                "She doesn't like coffee.",
                "She not like coffee.",
                "She doesn't likes coffee.",
            ],
            "correct_index": 1,
            "explanation": "Third-person singular subjects use 'doesn't' with the base form of the verb.",
        },
        {
            "question_text": "Which of these is a compound sentence?",
            "options": [
                "He ran fast, but he still lost the race.",
                "He ran fast.",
                "Running fast, he won.",
                "The fast runner.",
            ],
            "correct_index": 0,
            "explanation": "A compound sentence joins two independent clauses with a coordinating conjunction like 'but'.",
        },
        {
            "question_text": "Choose the correctly spelled word.",
            "options": ["Necessary", "Neccessary", "Necesary", "Neccesary"],
            "correct_index": 0,
            "explanation": "'Necessary' has one 'c' and two 's's — a commonly misspelled word.",
        },
        {
            "question_text": "Identify the noun clause in: 'I know that he is honest.'",
            "options": ["that he is honest", "I know", "he is honest", "is honest"],
            "correct_index": 0,
            "explanation": "'That he is honest' functions as the object of 'know', making it a noun clause.",
        },
        {
            "question_text": "Choose the correct article: '___ university is a place of higher learning.'",
            "options": ["A", "An", "The", "No article"],
            "correct_index": 0,
            "explanation": "'University' begins with a consonant sound (/juː/), so it takes 'a', not 'an'.",
        },
        {
            "question_text": "Choose the correct form: 'If I ___ rich, I would travel the world.'",
            "options": ["were", "was", "am", "will be"],
            "correct_index": 0,
            "explanation": "In second conditional sentences, 'were' is used for all subjects regardless of number.",
        },
        {
            "question_text": "Identify the type of sentence: 'What a beautiful sunset it is!'",
            "options": ["Exclamatory", "Interrogative", "Imperative", "Declarative"],
            "correct_index": 0,
            "explanation": "Sentences expressing strong emotion and ending with an exclamation mark are exclamatory.",
        },
        {
            "question_text": "Choose the correct preposition: 'She is good ___ mathematics.'",
            "options": ["at", "in", "on", "with"],
            "correct_index": 0,
            "explanation": "The idiomatic preposition used with 'good' for skills/subjects is 'at'.",
        },
        {
            "question_text": "Choose the synonym of 'Diligent'.",
            "options": ["Hardworking", "Lazy", "Careless", "Slow"],
            "correct_index": 0,
            "explanation": "'Diligent' means showing care and effort, which is closest to 'hardworking'.",
        },
        {
            "question_text": "Identify the correctly formed question tag: 'You are coming, ___?'",
            "options": ["aren't you", "are you", "don't you", "won't you"],
            "correct_index": 0,
            "explanation": "A positive statement takes a negative question tag; 'are' becomes 'aren't you'.",
        },
        {
            "question_text": "Which conditional type is: 'If it rains, the match will be cancelled.'?",
            "options": ["First conditional", "Second conditional", "Third conditional", "Zero conditional"],
            "correct_index": 0,
            "explanation": "This describes a real, likely future situation using 'if + present simple, will + base verb', the first conditional.",
        },
        {
            "question_text": "Identify the modal verb in: 'You must submit the assignment on time.'",
            "options": ["must", "submit", "assignment", "time"],
            "correct_index": 0,
            "explanation": "'Must' is a modal verb expressing obligation.",
        },
        {
            "question_text": "Choose the correct comparative form of 'good'.",
            "options": ["better", "gooder", "more good", "best"],
            "correct_index": 0,
            "explanation": "'Good' has an irregular comparative form, 'better' (and superlative 'best').",
        },
        {
            "question_text": "Identify the subject in: 'The old man in the park feeds the pigeons every morning.'",
            "options": ["The old man", "the park", "the pigeons", "every morning"],
            "correct_index": 0,
            "explanation": "'The old man' (modified by 'in the park') is who performs the action 'feeds', making it the subject.",
        },
    ],
    "Computer Science": [
        {
            "question_text": "Which of the following is an input device?",
            "options": ["Keyboard", "Monitor", "Printer", "Speaker"],
            "correct_index": 0,
            "explanation": "A keyboard sends data into the computer, making it an input device; the others are output devices.",
        },
        {
            "question_text": "What is the binary equivalent of decimal 10?",
            "options": ["1010", "1001", "1100", "1011"],
            "correct_index": 0,
            "explanation": "10 in decimal equals 8+2, i.e., 1010 in binary.",
        },
        {
            "question_text": "Which symbol is used for a single-line comment in Python?",
            "options": ["#", "//", "/* */", "--"],
            "correct_index": 0,
            "explanation": "Python uses the hash symbol (#) to mark single-line comments.",
        },
        {
            "question_text": "Which of the following is a mutable data type in Python?",
            "options": ["List", "Tuple", "String", "Integer"],
            "correct_index": 0,
            "explanation": "Lists can be modified in place after creation, unlike tuples, strings, and integers, which are immutable.",
        },
        {
            "question_text": "Which keyword is used to define a function in Python?",
            "options": ["def", "function", "func", "define"],
            "correct_index": 0,
            "explanation": "Python functions are defined using the 'def' keyword.",
        },
        {
            "question_text": "What is the output of len(\"Python\")?",
            "options": ["6", "5", "7", "Error"],
            "correct_index": 0,
            "explanation": "The string 'Python' has 6 characters, so len() returns 6.",
        },
        {
            "question_text": "Which data type is used to store key-value pairs in Python?",
            "options": ["Dictionary", "List", "Tuple", "Set"],
            "correct_index": 0,
            "explanation": "Dictionaries in Python store data as key-value pairs.",
        },
        {
            "question_text": "Which loop is typically used when the number of iterations is known in advance?",
            "options": ["for loop", "while loop", "do-while loop", "infinite loop"],
            "correct_index": 0,
            "explanation": "A 'for' loop is well-suited to iterating a known number of times, such as over a range or sequence.",
        },
        {
            "question_text": "The 'if-else' statement in programming represents:",
            "options": ["Conditional/decision control", "Looping", "A function call", "Variable declaration"],
            "correct_index": 0,
            "explanation": "'if-else' statements let a program choose between different paths based on a condition.",
        },
        {
            "question_text": "In Python, indexing of a list starts from:",
            "options": ["0", "1", "-1", "It is unindexed"],
            "correct_index": 0,
            "explanation": "Python uses zero-based indexing, so the first element is at index 0.",
        },
        {
            "question_text": "Which operator is used for exponentiation in Python?",
            "options": ["**", "^", "%%", "//"],
            "correct_index": 0,
            "explanation": "The double asterisk (**) is Python's exponentiation operator.",
        },
        {
            "question_text": "The full form of SDLC is:",
            "options": [
                "Software Development Life Cycle",
                "System Design Life Cycle",
                "Software Design Logic Circuit",
                "System Development Logical Chart",
            ],
            "correct_index": 0,
            "explanation": "SDLC stands for Software Development Life Cycle, the process used to plan and build software.",
        },
        {
            "question_text": "Boolean algebra uses which two values?",
            "options": ["0 and 1", "0 and -1", "1 and 2", "True and Maybe"],
            "correct_index": 0,
            "explanation": "Boolean algebra operates on binary values, typically represented as 0 (False) and 1 (True).",
        },
        {
            "question_text": "The AND operation in boolean algebra gives a result of 1 only when:",
            "options": ["Both inputs are 1", "Either input is 1", "Both inputs are 0", "One input is 0"],
            "correct_index": 0,
            "explanation": "The AND gate outputs 1 only if all its inputs are 1.",
        },
        {
            "question_text": "Which of the following is an immutable sequence type in Python?",
            "options": ["Tuple", "List", "Dictionary", "Set"],
            "correct_index": 0,
            "explanation": "Tuples cannot be changed after creation, unlike lists, dictionaries, and sets.",
        },
        {
            "question_text": "What does the % operator do in Python?",
            "options": [
                "Returns the remainder of a division",
                "Performs multiplication",
                "Performs floor division",
                "Performs exponentiation",
            ],
            "correct_index": 0,
            "explanation": "The modulo operator (%) returns the remainder after dividing one number by another.",
        },
        {
            "question_text": "Which of these correctly creates an empty list in Python?",
            "options": ["[]", "{}", "()", "None()"],
            "correct_index": 0,
            "explanation": "Square brackets with nothing inside, [], create an empty list.",
        },
        {
            "question_text": "Which SDLC phase primarily involves gathering user needs?",
            "options": ["Requirement analysis", "Testing", "Deployment", "Maintenance"],
            "correct_index": 0,
            "explanation": "The requirement analysis phase focuses on understanding and documenting what users need from the software.",
        },
        {
            "question_text": "Which of the following converts a string to an integer in Python?",
            "options": ["int()", "str()", "float()", "list()"],
            "correct_index": 0,
            "explanation": "The int() function converts a valid numeric string into an integer.",
        },
        {
            "question_text": "RAM stands for:",
            "options": ["Random Access Memory", "Read Access Memory", "Run Access Memory", "Rapid Access Memory"],
            "correct_index": 0,
            "explanation": "RAM is Random Access Memory, the computer's temporary, high-speed working memory.",
        },
    ],
}
