QUESTIONS: dict[str, list[dict]] = {
    "Physics": [
        {
            "question_text": "Coulomb's law states that the force between two point charges is proportional to the product of the charges and inversely proportional to:",
            "options": ["the distance between them", "the square of the distance between them", "the cube of the distance between them", "the sum of the charges"],
            "correct_index": 1,
            "explanation": "Coulomb's law gives F proportional to q1*q2/r^2, an inverse-square law.",
        },
        {
            "question_text": "What is the SI unit of electric field intensity?",
            "options": ["N/C", "C/N", "J/C", "C/m"],
            "correct_index": 0,
            "explanation": "Electric field is force per unit charge, measured in newton per coulomb (N/C).",
        },
        {
            "question_text": "Inserting a dielectric between the plates of a parallel plate capacitor increases its capacitance because the dielectric:",
            "options": ["increases the plate separation", "reduces the net electric field between the plates for the same charge", "increases the charge stored automatically", "decreases the permittivity of the medium"],
            "correct_index": 1,
            "explanation": "The dielectric polarizes and opposes the field, lowering V for the same Q, so C = Q/V rises.",
        },
        {
            "question_text": "Ohm's law relates voltage (V), current (I), and resistance (R) as:",
            "options": ["V = IR", "V = I/R", "V = I + R", "V = I^2 R"],
            "correct_index": 0,
            "explanation": "Ohm's law states V = IR for an ohmic conductor at constant temperature.",
        },
        {
            "question_text": "Kirchhoff's junction (current) rule at any node in a circuit is a statement of conservation of:",
            "options": ["energy", "electric charge", "momentum", "mass"],
            "correct_index": 1,
            "explanation": "Since charge cannot accumulate at a junction, total current in equals total current out.",
        },
        {
            "question_text": "A charge q moving with speed v at angle theta to a magnetic field B experiences a force of magnitude:",
            "options": ["qvB sin(theta)", "qvB cos(theta)", "qvB tan(theta)", "qvB"],
            "correct_index": 0,
            "explanation": "The magnetic force is F = qv x B, whose magnitude is qvB sin(theta).",
        },
        {
            "question_text": "A magnetic material with a small negative susceptibility, which is weakly repelled by a magnetic field, is called:",
            "options": ["ferromagnetic", "paramagnetic", "diamagnetic", "non-magnetic"],
            "correct_index": 2,
            "explanation": "Diamagnetic materials have small negative susceptibility and are weakly repelled by magnetic fields.",
        },
        {
            "question_text": "Lenz's law, which gives the direction of an induced EMF, is a direct consequence of the conservation of:",
            "options": ["charge", "energy", "momentum", "mass"],
            "correct_index": 1,
            "explanation": "The induced current opposes the change producing it, consistent with conservation of energy.",
        },
        {
            "question_text": "In an AC circuit, the power factor cos(phi) refers to the cosine of:",
            "options": ["the phase difference between voltage and current", "the peak voltage", "the RMS current", "the source frequency"],
            "correct_index": 0,
            "explanation": "Power factor is cos(phi), where phi is the phase angle between the voltage and current.",
        },
        {
            "question_text": "Electromagnetic waves are transverse waves in which:",
            "options": ["only the electric field oscillates", "only the magnetic field oscillates", "the electric and magnetic fields oscillate perpendicular to each other and to the direction of propagation", "the electric and magnetic fields oscillate along the direction of propagation"],
            "correct_index": 2,
            "explanation": "E and B oscillate mutually perpendicular and perpendicular to the propagation direction, making the wave transverse.",
        },
        {
            "question_text": "A real image formed by a single convex (converging) lens is always:",
            "options": ["virtual and erect", "inverted with respect to the object", "the same size as the object", "impossible to form"],
            "correct_index": 1,
            "explanation": "A real image produced by a simple converging lens is always inverted relative to the object.",
        },
        {
            "question_text": "Which phenomenon provides direct evidence for the wave nature of light?",
            "options": ["photoelectric effect", "interference", "Compton effect", "black body radiation"],
            "correct_index": 1,
            "explanation": "Interference (and diffraction) patterns can only be explained by treating light as a wave.",
        },
        {
            "question_text": "In the photoelectric effect, increasing the intensity of incident light (frequency kept constant, above threshold) increases:",
            "options": ["the maximum kinetic energy of the ejected electrons", "the number of photoelectrons emitted per second", "the threshold frequency of the metal", "the work function of the metal"],
            "correct_index": 1,
            "explanation": "More intense light means more photons per second, ejecting more electrons per second; KE_max depends on frequency, not intensity.",
        },
        {
            "question_text": "According to Bohr's model of the hydrogen atom, the angular momentum of an electron in the nth orbit is quantized as:",
            "options": ["nh/(2*pi)", "nh", "n^2 h", "h/(n*pi)"],
            "correct_index": 0,
            "explanation": "Bohr postulated that angular momentum mvr = nh/(2*pi), where n is a positive integer.",
        },
        {
            "question_text": "The spontaneous disintegration of unstable atomic nuclei, emitting particles or radiation, is called:",
            "options": ["nuclear fission", "nuclear fusion", "radioactivity", "ionization"],
            "correct_index": 2,
            "explanation": "Radioactivity is the spontaneous emission of particles or radiation from unstable nuclei.",
        },
        {
            "question_text": "Doping a pure semiconductor with a pentavalent impurity (like phosphorus) produces a:",
            "options": ["p-type semiconductor", "n-type semiconductor", "purely intrinsic semiconductor", "perfect insulator"],
            "correct_index": 1,
            "explanation": "A pentavalent dopant contributes extra free electrons, giving an n-type semiconductor.",
        },
        {
            "question_text": "Among conductors, semiconductors, and insulators, the energy gap between the valence and conduction bands is largest for:",
            "options": ["conductors", "semiconductors", "insulators", "it is the same for all three"],
            "correct_index": 2,
            "explanation": "Insulators have a very large forbidden energy gap, preventing electrons from reaching the conduction band.",
        },
        {
            "question_text": "A p-n junction diode is commonly used as a:",
            "options": ["signal amplifier", "rectifier", "self-sustained oscillator", "frequency modulator"],
            "correct_index": 1,
            "explanation": "A p-n junction diode conducts in one direction only, making it useful as a rectifier.",
        },
        {
            "question_text": "The electric potential due to an isolated point charge, measured at an infinite distance from it, is conventionally taken to be:",
            "options": ["maximum", "zero", "negative infinity", "equal to the magnitude of the charge"],
            "correct_index": 1,
            "explanation": "Electric potential is conventionally defined to be zero at infinite distance from the charge.",
        },
        {
            "question_text": "Gauss's law relates the total electric flux through a closed surface to:",
            "options": ["the electric field on the surface", "the net electric charge enclosed by the surface", "the total surface area", "the potential difference across the surface"],
            "correct_index": 1,
            "explanation": "Gauss's law states that flux through a closed surface equals the enclosed charge divided by epsilon_0.",
        },
    ],
    "Chemistry": [
        {
            "question_text": "Molality of a solution is defined as the number of moles of solute per:",
            "options": ["litre of solution", "kilogram of solvent", "mole of solvent", "litre of solvent"],
            "correct_index": 1,
            "explanation": "Molality is defined as moles of solute divided by the mass of solvent in kilograms.",
        },
        {
            "question_text": "According to Raoult's law, the partial vapour pressure of a volatile component in an ideal solution is:",
            "options": ["proportional to its mole fraction in the solution", "independent of its mole fraction", "inversely proportional to its mole fraction", "always equal to the vapour pressure of the pure component"],
            "correct_index": 0,
            "explanation": "Raoult's law states partial pressure equals mole fraction times the pure component's vapour pressure.",
        },
        {
            "question_text": "In an electrochemical (galvanic) cell, oxidation takes place at the:",
            "options": ["cathode", "anode", "salt bridge", "external wire"],
            "correct_index": 1,
            "explanation": "By convention, oxidation (loss of electrons) occurs at the anode in an electrochemical cell.",
        },
        {
            "question_text": "The SI unit of molar conductivity is:",
            "options": ["S m^2 mol^-1", "S m^-1", "S mol^-1", "S m"],
            "correct_index": 0,
            "explanation": "Molar conductivity has SI units of siemens metre-squared per mole (S m^2 mol^-1).",
        },
        {
            "question_text": "For a reaction of first order, the half-life period is:",
            "options": ["dependent on the initial concentration", "independent of the initial concentration", "directly proportional to the initial concentration", "inversely proportional to the square of the rate constant"],
            "correct_index": 1,
            "explanation": "First-order half-life is t(1/2) = 0.693/k, which does not depend on initial concentration.",
        },
        {
            "question_text": "Transition elements are characterised by electrons partially filling the:",
            "options": ["s orbitals", "p orbitals", "d orbitals", "f orbitals"],
            "correct_index": 2,
            "explanation": "Transition elements have incompletely filled d orbitals in their atoms or common ions.",
        },
        {
            "question_text": "In coordination compounds, the number of ligand donor atoms directly bonded to the central metal atom/ion is called its:",
            "options": ["oxidation number", "coordination number", "valency", "atomic number"],
            "correct_index": 1,
            "explanation": "The coordination number counts the ligand atoms directly bonded to the central metal atom.",
        },
        {
            "question_text": "Haloalkanes react with alcoholic KOH mainly to undergo:",
            "options": ["substitution, forming an alcohol", "elimination, forming an alkene", "an addition reaction", "no reaction at all"],
            "correct_index": 1,
            "explanation": "Alcoholic KOH favours dehydrohalogenation (elimination), producing an alkene.",
        },
        {
            "question_text": "Phenol is more acidic than ethanol mainly because:",
            "options": ["the phenoxide ion is stabilised by resonance", "phenol has a higher molecular weight", "ethanol is more polar than phenol", "phenol lacks an -OH group"],
            "correct_index": 0,
            "explanation": "Resonance delocalisation of the negative charge stabilises the phenoxide ion, increasing phenol's acidity.",
        },
        {
            "question_text": "Aldehydes and ketones both contain which functional group?",
            "options": ["carboxyl group", "carbonyl group", "hydroxyl group", "amino group"],
            "correct_index": 1,
            "explanation": "Both aldehydes and ketones contain the carbonyl group, C=O.",
        },
        {
            "question_text": "The reaction of a carboxylic acid with an alcohol in the presence of an acid catalyst, forming an ester, is called:",
            "options": ["saponification", "esterification", "hydrolysis", "oxidation"],
            "correct_index": 1,
            "explanation": "Esterification is the acid-catalysed reaction of a carboxylic acid with an alcohol to give an ester.",
        },
        {
            "question_text": "Amines generally behave as:",
            "options": ["strong acids", "weak bases due to the lone pair on nitrogen", "neutral compounds only", "strong oxidising agents"],
            "correct_index": 1,
            "explanation": "The lone pair on the nitrogen atom lets amines accept a proton, making them weak Lewis/Bronsted bases.",
        },
        {
            "question_text": "Which of the following is a carbohydrate?",
            "options": ["glucose", "glycine", "cholesterol", "adenine"],
            "correct_index": 0,
            "explanation": "Glucose is a monosaccharide, a simple carbohydrate.",
        },
        {
            "question_text": "Proteins are biological polymers built from monomer units called:",
            "options": ["nucleotides", "amino acids", "monosaccharides", "fatty acids"],
            "correct_index": 1,
            "explanation": "Proteins are polypeptides formed by amino acid monomers linked by peptide bonds.",
        },
        {
            "question_text": "Nylon-6,6, formed from hexamethylenediamine and adipic acid, is an example of a:",
            "options": ["natural polymer", "synthetic addition polymer", "synthetic condensation polymer", "purely inorganic polymer"],
            "correct_index": 2,
            "explanation": "Nylon-6,6 forms by condensation polymerisation, releasing water as the monomers link.",
        },
        {
            "question_text": "Which of the following is commonly used as an antipyretic (fever-reducing) drug?",
            "options": ["paracetamol", "penicillin", "insulin", "ranitidine"],
            "correct_index": 0,
            "explanation": "Paracetamol is a widely used antipyretic and analgesic drug.",
        },
        {
            "question_text": "Antibiotics function primarily by:",
            "options": ["killing or inhibiting the growth of microorganisms", "increasing blood sugar levels", "reducing body temperature directly", "acting as a food preservative"],
            "correct_index": 0,
            "explanation": "Antibiotics act against bacteria and other microorganisms by killing them or stopping their growth.",
        },
        {
            "question_text": "The rate constant of a zero-order reaction has the same units as the:",
            "options": ["rate of reaction", "equilibrium constant", "time", "rate constant of a first-order reaction"],
            "correct_index": 0,
            "explanation": "For a zero-order reaction, rate = k, so k carries the same units as the rate itself (mol L^-1 s^-1).",
        },
        {
            "question_text": "Which of the following is a strong electrolyte that dissociates almost completely in water?",
            "options": ["sodium chloride (NaCl)", "acetic acid", "ammonia solution", "glucose solution"],
            "correct_index": 0,
            "explanation": "NaCl is an ionic compound that fully dissociates into Na+ and Cl- ions in water, making it a strong electrolyte.",
        },
        {
            "question_text": "Lanthanoid contraction refers to the:",
            "options": ["steady increase in atomic and ionic radii across the lanthanoid series", "steady decrease in atomic and ionic radii across the lanthanoid series", "sudden expansion of d-orbitals in lanthanoids", "increase in oxidation states across the series"],
            "correct_index": 1,
            "explanation": "Poor shielding by 4f electrons causes a steady decrease in atomic/ionic radii across the lanthanoid series.",
        },
    ],
    "Mathematics": [
        {
            "question_text": "A relation R on a set A is called reflexive if:",
            "options": ["(a, a) belongs to R for every a in A", "(a, b) in R implies (b, a) in R", "(a, b) and (b, c) in R implies (a, c) in R", "R is the empty set"],
            "correct_index": 0,
            "explanation": "Reflexivity requires every element to be related to itself.",
        },
        {
            "question_text": "The principal value branch of sin^-1(x) is:",
            "options": ["[0, pi]", "[-pi/2, pi/2]", "(-pi, pi)", "[0, 2*pi]"],
            "correct_index": 1,
            "explanation": "The principal branch of sin^-1(x) is conventionally taken as [-pi/2, pi/2].",
        },
        {
            "question_text": "If a square matrix A satisfies A^2 = A, then A is called:",
            "options": ["symmetric", "idempotent", "orthogonal", "skew-symmetric"],
            "correct_index": 1,
            "explanation": "A matrix satisfying A^2 = A is by definition called idempotent.",
        },
        {
            "question_text": "The determinant of the 2x2 matrix [[a, b], [c, d]] is:",
            "options": ["ad + bc", "ad - bc", "ac - bd", "ab - cd"],
            "correct_index": 1,
            "explanation": "For a 2x2 matrix, the determinant is the product of the main diagonal minus the product of the other diagonal: ad - bc.",
        },
        {
            "question_text": "A function f is continuous at x = a if:",
            "options": ["f(a) is defined only", "the limit as x approaches a exists only", "the limit of f(x) as x approaches a equals f(a)", "f is differentiable at a"],
            "correct_index": 2,
            "explanation": "Continuity at a point requires the limit at that point to exist and equal the function's value there.",
        },
        {
            "question_text": "The derivative of x^n with respect to x is:",
            "options": ["n*x^(n-1)", "x^(n-1)", "n*x^n", "(n-1)*x^n"],
            "correct_index": 0,
            "explanation": "The power rule states d/dx(x^n) = n*x^(n-1).",
        },
        {
            "question_text": "A function f has a local maximum at x = c if f'(c) = 0 and:",
            "options": ["f''(c) > 0", "f''(c) < 0", "f''(c) = 0", "f'(c) is undefined"],
            "correct_index": 1,
            "explanation": "By the second derivative test, f''(c) < 0 at a critical point indicates a local maximum.",
        },
        {
            "question_text": "The indefinite integral of 1/x with respect to x is:",
            "options": ["ln|x| + C", "x^2/2 + C", "1/x^2 + C", "e^x + C"],
            "correct_index": 0,
            "explanation": "The antiderivative of 1/x is the natural logarithm of |x|, plus a constant of integration.",
        },
        {
            "question_text": "The area bounded by a curve y = f(x), the x-axis, and the lines x = a and x = b is given by:",
            "options": ["the definite integral of f(x) from a to b", "f(b) - f(a)", "the definite integral of f'(x) from a to b", "pi times the square of the radius"],
            "correct_index": 0,
            "explanation": "The area under a curve between two x-values is computed as the definite integral of the function over that interval.",
        },
        {
            "question_text": "The order of a differential equation is defined as:",
            "options": ["the exponent of the highest derivative present", "the power of the independent variable", "the order of the highest-order derivative present", "the number of arbitrary constants in its solution"],
            "correct_index": 2,
            "explanation": "The order of a differential equation is the order of the highest derivative appearing in it.",
        },
        {
            "question_text": "The magnitude of the vector a = x*i + y*j + z*k is:",
            "options": ["x + y + z", "the square root of (x^2 + y^2 + z^2)", "x^2 + y^2 + z^2", "xy + yz + zx"],
            "correct_index": 1,
            "explanation": "The magnitude of a 3D vector is found using the Pythagorean sum of its components under a square root.",
        },
        {
            "question_text": "Two vectors are perpendicular to each other when their:",
            "options": ["cross product is zero", "dot product is zero", "magnitudes are equal", "sum is the zero vector"],
            "correct_index": 1,
            "explanation": "Two nonzero vectors are perpendicular exactly when their dot product equals zero.",
        },
        {
            "question_text": "The direction cosines l, m, n of a line in space always satisfy:",
            "options": ["l + m + n = 1", "l^2 + m^2 + n^2 = 1", "l * m * n = 1", "l^2 + m^2 + n^2 = 0"],
            "correct_index": 1,
            "explanation": "Direction cosines are defined so that the sum of their squares always equals 1.",
        },
        {
            "question_text": "In a Linear Programming Problem, the region satisfying all the given constraints simultaneously is called the:",
            "options": ["objective function", "feasible region", "optimal solution", "boundary condition"],
            "correct_index": 1,
            "explanation": "The feasible region is the set of all points satisfying every constraint of the LPP.",
        },
        {
            "question_text": "In a Linear Programming Problem, the optimal value of the objective function occurs at:",
            "options": ["the origin, always", "the centroid of the feasible region", "a corner point (vertex) of the feasible region", "any arbitrary point inside the region"],
            "correct_index": 2,
            "explanation": "By the fundamental theorem of LPP, the optimum of a linear objective function occurs at a vertex of the feasible region.",
        },
        {
            "question_text": "The conditional probability P(A|B) is defined as:",
            "options": ["P(A intersect B) / P(B)", "P(A union B) / P(B)", "P(A) / P(B)", "P(B) / P(A)"],
            "correct_index": 0,
            "explanation": "Conditional probability of A given B is defined as P(A intersect B) divided by P(B), for P(B) > 0.",
        },
        {
            "question_text": "Two events A and B are said to be independent if:",
            "options": ["P(A intersect B) = P(A) + P(B)", "P(A intersect B) = P(A) * P(B)", "P(A intersect B) = 0", "P(A|B) = P(B)"],
            "correct_index": 1,
            "explanation": "Independence of events A and B means the probability of both occurring equals the product of their individual probabilities.",
        },
        {
            "question_text": "Bayes' theorem is primarily used to find:",
            "options": ["an unconditional probability", "a reverse conditional probability given known conditional probabilities", "the mean of a probability distribution", "the variance of a probability distribution"],
            "correct_index": 1,
            "explanation": "Bayes' theorem lets you compute P(A|B) from P(B|A) and the prior probabilities of A and B.",
        },
        {
            "question_text": "The derivative of sin(x) with respect to x is:",
            "options": ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"],
            "correct_index": 0,
            "explanation": "By the standard rules of differentiation, d/dx(sin x) = cos x.",
        },
        {
            "question_text": "A square matrix that is equal to its own transpose is called:",
            "options": ["skew-symmetric", "symmetric", "orthogonal", "singular"],
            "correct_index": 1,
            "explanation": "A matrix A satisfying A = A^T (its transpose) is defined as symmetric.",
        },
    ],
    "Biology": [
        {
            "question_text": "Asexual reproduction by budding, where a new individual grows out from the body of the parent, is commonly seen in:",
            "options": ["Hydra", "humans", "frogs", "birds"],
            "correct_index": 0,
            "explanation": "Hydra reproduces asexually by budding, forming a new individual that eventually detaches.",
        },
        {
            "question_text": "In flowering plants, the male gametophyte is represented by the:",
            "options": ["ovule", "pollen grain", "embryo sac", "anther wall"],
            "correct_index": 1,
            "explanation": "The pollen grain, produced within the anther, is the male gametophyte of a flowering plant.",
        },
        {
            "question_text": "Double fertilisation in angiosperms results in the formation of:",
            "options": ["only the zygote", "the zygote and the primary endosperm nucleus", "only the endosperm", "only the embryo sac"],
            "correct_index": 1,
            "explanation": "One male gamete fertilises the egg to form the zygote; the other fuses with polar nuclei to form the primary endosperm nucleus.",
        },
        {
            "question_text": "In the human female reproductive system, fertilisation of the egg normally occurs in the:",
            "options": ["uterus", "fallopian tube (oviduct)", "ovary", "vagina"],
            "correct_index": 1,
            "explanation": "Sperm typically meet and fertilise the egg in the ampullary region of the fallopian tube.",
        },
        {
            "question_text": "Which of these is a barrier method of contraception?",
            "options": ["condom", "a course of antibiotics", "a vaccination", "a vitamin supplement"],
            "correct_index": 0,
            "explanation": "A condom physically prevents sperm from reaching the egg, making it a barrier contraceptive method.",
        },
        {
            "question_text": "Mendel's Law of Segregation states that:",
            "options": ["alleles of different genes assort independently of one another", "the two alleles of a gene separate from each other during gamete formation", "one allele is always dominant over the other", "traits always blend in the offspring"],
            "correct_index": 1,
            "explanation": "The Law of Segregation says the paired alleles for a trait separate during the formation of gametes.",
        },
        {
            "question_text": "DNA replication is described as semiconservative because each resulting daughter DNA molecule:",
            "options": ["is made entirely of newly synthesised strands", "has one parental strand and one newly synthesised strand", "is made entirely from the parental strands", "consists only of RNA"],
            "correct_index": 1,
            "explanation": "In semiconservative replication, each new DNA double helix retains one original (parental) strand and gains one new strand.",
        },
        {
            "question_text": "Transcription in a cell produces:",
            "options": ["DNA from an RNA template", "protein directly from an RNA template", "RNA using a DNA template", "DNA using another DNA molecule as template"],
            "correct_index": 2,
            "explanation": "Transcription is the process by which an RNA molecule is synthesised using a DNA strand as the template.",
        },
        {
            "question_text": "The theory of evolution by natural selection was proposed by:",
            "options": ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Robert Hooke"],
            "correct_index": 1,
            "explanation": "Charles Darwin proposed natural selection as the primary mechanism driving evolution.",
        },
        {
            "question_text": "Malaria, transmitted by the female Anopheles mosquito, is caused by a:",
            "options": ["protozoan parasite (Plasmodium)", "bacterium", "virus", "fungus"],
            "correct_index": 0,
            "explanation": "Malaria is caused by Plasmodium, a protozoan parasite transmitted through the bite of an infected female Anopheles mosquito.",
        },
        {
            "question_text": "AIDS (Acquired Immunodeficiency Syndrome) is caused by:",
            "options": ["a bacterium", "a fungus", "HIV, a virus", "a protozoan"],
            "correct_index": 2,
            "explanation": "AIDS is caused by infection with the Human Immunodeficiency Virus (HIV).",
        },
        {
            "question_text": "The antibiotic penicillin is naturally obtained from a species of:",
            "options": ["bacteria", "fungus (Penicillium)", "virus", "alga"],
            "correct_index": 1,
            "explanation": "Penicillin was originally isolated from the mould fungus Penicillium notatum.",
        },
        {
            "question_text": "The souring/curdling of milk into curd is mainly due to the activity of:",
            "options": ["Lactobacillus bacteria", "yeast", "Penicillium", "Escherichia coli"],
            "correct_index": 0,
            "explanation": "Lactobacillus bacteria ferment lactose to lactic acid, curdling milk into curd.",
        },
        {
            "question_text": "Restriction enzymes used in genetic engineering to cut DNA at specific sequences are commonly nicknamed:",
            "options": ["molecular scissors", "DNA polymerase", "ligase", "primers"],
            "correct_index": 0,
            "explanation": "Restriction enzymes cut DNA at specific recognition sites, earning them the nickname 'molecular scissors'.",
        },
        {
            "question_text": "In recombinant DNA technology, foreign DNA is commonly introduced into bacterial cells using a:",
            "options": ["plasmid vector", "ribosome", "mitochondrion", "cell nucleus"],
            "correct_index": 0,
            "explanation": "Plasmids are small circular DNA molecules commonly used as vectors to carry foreign DNA into bacteria.",
        },
        {
            "question_text": "Bt cotton has been genetically modified to be resistant to:",
            "options": ["drought conditions", "certain insect pests, such as the bollworm", "frost damage", "all types of herbicides"],
            "correct_index": 1,
            "explanation": "Bt cotton carries a gene from Bacillus thuringiensis that produces a toxin lethal to bollworm and similar insect pests.",
        },
        {
            "question_text": "A group of individuals of the same species living together in a defined geographical area is called a:",
            "options": ["population", "community", "ecosystem", "biome"],
            "correct_index": 0,
            "explanation": "A population is defined as all the individuals of one species occupying a particular area.",
        },
        {
            "question_text": "In an ecosystem, the flow of energy through the food chain is always:",
            "options": ["cyclic", "unidirectional", "bidirectional", "random"],
            "correct_index": 1,
            "explanation": "Unlike nutrients, energy flows in only one direction through an ecosystem, from producers to higher trophic levels, and is not recycled.",
        },
        {
            "question_text": "Species that are found only in one particular geographic region and nowhere else in the world are called:",
            "options": ["endemic species", "exotic species", "invasive species", "keystone species"],
            "correct_index": 0,
            "explanation": "Endemic species are native and restricted to a specific geographic region.",
        },
        {
            "question_text": "In-situ conservation of biodiversity is achieved mainly through:",
            "options": ["seed banks", "zoos", "national parks and wildlife sanctuaries", "botanical gardens"],
            "correct_index": 2,
            "explanation": "In-situ conservation protects species within their natural habitat, such as in national parks and wildlife sanctuaries.",
        },
    ],
    "English": [
        {
            "question_text": "Choose the correctly formed passive voice of: 'The manager will finalize the report tomorrow.'",
            "options": ["The report will be finalized by the manager tomorrow.", "The report was finalized by the manager tomorrow.", "The report is finalized by the manager tomorrow.", "The report will finalize by the manager tomorrow."],
            "correct_index": 0,
            "explanation": "Future simple active ('will finalize') becomes future simple passive: 'will be finalized'.",
        },
        {
            "question_text": "Change into indirect (reported) speech: She said, 'I am writing a letter.'",
            "options": ["She said that she is writing a letter.", "She said that she was writing a letter.", "She said that she wrote a letter.", "She says that she was writing a letter."],
            "correct_index": 1,
            "explanation": "In reported speech, present continuous ('am writing') shifts back to past continuous ('was writing').",
        },
        {
            "question_text": "Which sentence is grammatically correct?",
            "options": ["Neither of the students have submitted their assignment.", "Neither of the students has submitted his or her assignment.", "Neither of the student has submit assignment.", "Neither of the students submitting assignment."],
            "correct_index": 1,
            "explanation": "'Neither' is singular, so it takes a singular verb ('has') and a matching singular pronoun.",
        },
        {
            "question_text": "Choose the word that best completes: 'The committee could not reach a ______ decision after hours of debate.'",
            "options": ["unanimous", "unanimously", "unanimity", "unanimousness"],
            "correct_index": 0,
            "explanation": "'Unanimous' is the adjective needed to modify the noun 'decision'.",
        },
        {
            "question_text": "Identify the type of clause in: 'I know that he is honest.'",
            "options": ["adjective clause", "noun clause", "adverb clause", "an independent clause"],
            "correct_index": 1,
            "explanation": "'That he is honest' functions as the object of 'know', so it is a noun clause.",
        },
        {
            "question_text": "Choose the correct form to complete: 'By this time next year, she ______ her degree.'",
            "options": ["will complete", "will have completed", "completes", "is completing"],
            "correct_index": 1,
            "explanation": "An action finished before a specific future point uses the future perfect tense: 'will have completed'.",
        },
        {
            "question_text": "Identify the correction needed in: 'Each of the boys have brought their own lunch.'",
            "options": ["'Each' should be changed to 'All'", "'have' should be changed to 'has'", "'their' should be changed to 'his or her'", "both the verb and the pronoun need correcting"],
            "correct_index": 3,
            "explanation": "'Each' is singular, so it needs the singular verb 'has' and, strictly, a singular pronoun.",
        },
        {
            "question_text": "Choose the antonym of 'benevolent':",
            "options": ["kind", "malevolent", "generous", "charitable"],
            "correct_index": 1,
            "explanation": "'Malevolent' (wishing harm) is the opposite of 'benevolent' (kind and well-meaning).",
        },
        {
            "question_text": "Choose the word closest in meaning to 'meticulous':",
            "options": ["careless", "careful and precise", "quick", "lazy"],
            "correct_index": 1,
            "explanation": "'Meticulous' means showing great attention to detail; very careful and precise.",
        },
        {
            "question_text": "Fill in the blank with the correct preposition: 'She has been living in Delhi ______ 2015.'",
            "options": ["since", "for", "from", "at"],
            "correct_index": 0,
            "explanation": "'Since' is used with a specific point in time (2015), while 'for' would be used with a duration.",
        },
        {
            "question_text": "Which sentence uses the correct conditional form?",
            "options": ["If I would have known, I would have come.", "If I had known, I would have come.", "If I knew, I would have come earlier yesterday.", "If I have known, I will come."],
            "correct_index": 1,
            "explanation": "A third conditional (unreal past) needs 'If + past perfect, ... would have + past participle'.",
        },
        {
            "question_text": "Choose the correctly spelled word:",
            "options": ["recieve", "receive", "receeve", "receve"],
            "correct_index": 1,
            "explanation": "The correct spelling follows 'i before e except after c': r-e-c-e-i-v-e.",
        },
        {
            "question_text": "Identify the figure of speech in: 'The wind whispered through the trees.'",
            "options": ["simile", "metaphor", "personification", "hyperbole"],
            "correct_index": 2,
            "explanation": "Giving the wind the human ability to 'whisper' is an example of personification.",
        },
        {
            "question_text": "Choose the correct question tag to complete: 'You will attend the meeting, ______?'",
            "options": ["will you", "won't you", "do you", "aren't you"],
            "correct_index": 1,
            "explanation": "A positive statement with 'will' takes a negative tag: 'won't you'.",
        },
        {
            "question_text": "Which word is a synonym for 'abundant'?",
            "options": ["scarce", "plentiful", "rare", "limited"],
            "correct_index": 1,
            "explanation": "'Abundant' means existing in large quantities, which matches 'plentiful'.",
        },
        {
            "question_text": "Which of these correctly combines the sentences 'He was tired.' and 'He continued working.' using a subordinating conjunction?",
            "options": ["Although he was tired, he continued working.", "He was tired, so he stopped working.", "Because he continued working, he was tired.", "He continued working, although stopped."],
            "correct_index": 0,
            "explanation": "'Although' correctly signals the contrast between being tired and continuing to work.",
        },
        {
            "question_text": "Choose the correct article to complete: 'She is ______ honest person.'",
            "options": ["a", "an", "the", "no article is needed"],
            "correct_index": 1,
            "explanation": "'Honest' begins with a silent 'h', so it takes the vowel-sound article 'an'.",
        },
        {
            "question_text": "Which of these is an example of a compound sentence?",
            "options": ["She sang and he danced.", "Although it rained, they played.", "She sang.", "The boy who won the race is my friend."],
            "correct_index": 0,
            "explanation": "A compound sentence joins two independent clauses with a coordinating conjunction, as in 'She sang and he danced.'",
        },
        {
            "question_text": "The idiom 'to burn the midnight oil' means:",
            "options": ["to waste time", "to work late into the night", "to start a fire", "to relax completely"],
            "correct_index": 1,
            "explanation": "'To burn the midnight oil' idiomatically means to work or study late into the night.",
        },
        {
            "question_text": "Identify the grammatically correct sentence:",
            "options": ["Neither the teacher nor the students was present.", "Neither the teacher nor the students were present.", "Neither the teacher or the students were present.", "Neither the teacher and the students were present."],
            "correct_index": 1,
            "explanation": "With 'neither...nor', the verb agrees with the nearer subject, here plural 'students', so 'were' is correct.",
        },
    ],
    "Computer Science": [
        {
            "question_text": "In Python, which keyword is used to define a function?",
            "options": ["func", "def", "function", "lambda"],
            "correct_index": 1,
            "explanation": "Python functions are defined using the 'def' keyword followed by the function name and parentheses.",
        },
        {
            "question_text": "A recursive function is one that:",
            "options": ["never terminates", "calls itself, directly or indirectly", "always runs inside a loop", "never has a return statement"],
            "correct_index": 1,
            "explanation": "Recursion occurs when a function calls itself, usually with a base case to stop the recursion.",
        },
        {
            "question_text": "Which file mode opens a file in Python for appending data to the end without erasing existing content?",
            "options": ["\"r\"", "\"w\"", "\"a\"", "\"x\""],
            "correct_index": 2,
            "explanation": "Mode \"a\" opens a file for appending; new data is written after existing content instead of overwriting it.",
        },
        {
            "question_text": "A module in Python is best described as:",
            "options": ["a file containing Python code that can be imported and reused", "a type of loop construct", "a built-in primitive data type", "a table inside a database"],
            "correct_index": 0,
            "explanation": "A Python module is simply a .py file containing definitions and statements that can be imported elsewhere.",
        },
        {
            "question_text": "A stack data structure follows which principle for adding and removing elements?",
            "options": ["First In First Out (FIFO)", "Last In First Out (LIFO)", "random access", "priority-based access"],
            "correct_index": 1,
            "explanation": "A stack removes the most recently added element first, which is the LIFO principle.",
        },
        {
            "question_text": "A queue data structure follows which principle for adding and removing elements?",
            "options": ["Last In First Out (LIFO)", "First In First Out (FIFO)", "random access", "always priority-based"],
            "correct_index": 1,
            "explanation": "A queue removes elements in the order they were added, which is the FIFO principle.",
        },
        {
            "question_text": "Which SQL clause is used to filter rows based on a specified condition?",
            "options": ["SELECT", "WHERE", "GROUP BY", "ORDER BY"],
            "correct_index": 1,
            "explanation": "The WHERE clause filters rows before they are returned, based on a Boolean condition.",
        },
        {
            "question_text": "Which SQL clause groups rows that share a value so aggregate functions like COUNT or SUM can be applied to each group?",
            "options": ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
            "correct_index": 2,
            "explanation": "GROUP BY groups rows sharing a common column value, enabling per-group aggregate calculations.",
        },
        {
            "question_text": "A SQL JOIN is used to:",
            "options": ["permanently delete rows from a table", "combine rows from two or more related tables", "sort the rows of a single table", "create a brand new empty database"],
            "correct_index": 1,
            "explanation": "JOIN combines rows from two or more tables based on a related column between them.",
        },
        {
            "question_text": "Which network device connects multiple devices within a LAN and forwards data frames based on MAC address?",
            "options": ["switch", "modem", "router", "repeater"],
            "correct_index": 0,
            "explanation": "A switch forwards frames within a LAN using MAC addresses to direct traffic to the correct device.",
        },
        {
            "question_text": "Which protocol is used to transfer and display web pages over the internet?",
            "options": ["FTP", "SMTP", "HTTP", "SNMP"],
            "correct_index": 2,
            "explanation": "HTTP (HyperText Transfer Protocol) is the protocol used to request and transfer web pages.",
        },
        {
            "question_text": "A network confined to a small geographical area, such as a single building or campus, is called a:",
            "options": ["WAN (Wide Area Network)", "LAN (Local Area Network)", "MAN (Metropolitan Area Network)", "internet backbone"],
            "correct_index": 1,
            "explanation": "A LAN spans a small area like an office, building, or campus.",
        },
        {
            "question_text": "A firewall is best described as:",
            "options": ["hardware or software that monitors and controls network traffic for security", "a type of computer virus", "a database management tool", "a programming language used for web development"],
            "correct_index": 0,
            "explanation": "A firewall filters incoming and outgoing network traffic based on security rules.",
        },
        {
            "question_text": "Plagiarism, an important cyber-ethics concept, refers to:",
            "options": ["sharing your own original work freely", "presenting someone else's work or ideas as your own", "using properly licensed open-source software", "regularly backing up your data"],
            "correct_index": 1,
            "explanation": "Plagiarism means passing off another person's work or ideas as one's own without credit.",
        },
        {
            "question_text": "Which of these is considered a cybercrime?",
            "options": ["sending a routine, legitimate email", "gaining unauthorized access to someone's computer system", "browsing a public website", "installing properly licensed software"],
            "correct_index": 1,
            "explanation": "Unauthorized access to a computer system (hacking) is a criminal offence under cyber law.",
        },
        {
            "question_text": "In Boolean algebra, A OR (NOT A) — that is, A + A' — always equals:",
            "options": ["0", "1", "A", "A'"],
            "correct_index": 1,
            "explanation": "A variable ORed with its own complement always evaluates to 1, by the complement law.",
        },
        {
            "question_text": "In Boolean algebra, A AND (NOT A) — that is, A . A' — always equals:",
            "options": ["0", "1", "A", "A'"],
            "correct_index": 0,
            "explanation": "A variable ANDed with its own complement always evaluates to 0, by the complement law.",
        },
        {
            "question_text": "According to De Morgan's theorem, (A + B)' is equal to:",
            "options": ["A' + B'", "A' . B'", "A . B", "A + B"],
            "correct_index": 1,
            "explanation": "De Morgan's theorem states that the complement of a sum equals the product of the complements: (A+B)' = A'.B'.",
        },
        {
            "question_text": "A primary key in a database table:",
            "options": ["can contain duplicate values", "uniquely identifies each record and cannot be NULL", "is always stored as a text field", "is optional and rarely used"],
            "correct_index": 1,
            "explanation": "A primary key uniquely identifies every row in a table and must never be NULL.",
        },
        {
            "question_text": "Which of the following built-in Python data types is immutable?",
            "options": ["list", "dictionary", "tuple", "set"],
            "correct_index": 2,
            "explanation": "A tuple's contents cannot be changed after creation, making it immutable; lists, dicts, and sets are mutable.",
        },
    ],
}
