QUESTIONS: dict[str, list[dict]] = {
    "Mathematics": [
        {
            "question_text": "What is the additive inverse of -5/7?",
            "options": ["5/7", "-5/7", "7/5", "-7/5"],
            "correct_index": 0,
            "explanation": "The additive inverse of a number x is -x, and -(-5/7) = 5/7.",
        },
        {
            "question_text": "Solve for x: 3x + 5 = 20.",
            "options": ["5", "15", "3", "25/3"],
            "correct_index": 0,
            "explanation": "Subtracting 5 gives 3x = 15, and dividing by 3 gives x = 5.",
        },
        {
            "question_text": "The sum of the interior angles of a quadrilateral is:",
            "options": ["180°", "270°", "360°", "540°"],
            "correct_index": 2,
            "explanation": "Any quadrilateral can be split into two triangles, so its angle sum is 2 x 180° = 360°.",
        },
        {
            "question_text": "A quadrilateral with all sides equal and opposite sides parallel, but angles not necessarily 90°, is called a:",
            "options": ["Square", "Rhombus", "Rectangle", "Trapezium"],
            "correct_index": 1,
            "explanation": "A rhombus has all four sides equal and opposite sides parallel, without requiring right angles.",
        },
        {
            "question_text": "Find the square root of 169.",
            "options": ["11", "12", "13", "14"],
            "correct_index": 2,
            "explanation": "13 x 13 = 169, so the square root of 169 is 13.",
        },
        {
            "question_text": "Which of these is a perfect cube?",
            "options": ["16", "27", "48", "90"],
            "correct_index": 1,
            "explanation": "27 = 3 x 3 x 3 = 3 cubed, making it a perfect cube.",
        },
        {
            "question_text": "Find the value of 2 to the power -3.",
            "options": ["8", "-8", "1/8", "-1/8"],
            "correct_index": 2,
            "explanation": "A negative exponent means the reciprocal: 2^-3 = 1/(2^3) = 1/8.",
        },
        {
            "question_text": "If Rs. 5000 is invested at 10% per annum compound interest for 2 years, the final amount is:",
            "options": ["Rs. 6000", "Rs. 6050", "Rs. 6100", "Rs. 6200"],
            "correct_index": 1,
            "explanation": "Amount = 5000 x (1.1)^2 = 5000 x 1.21 = Rs. 6050.",
        },
        {
            "question_text": "Factorise: x squared - 9.",
            "options": ["(x - 3)(x + 3)", "(x - 9)(x + 1)", "(x - 3) squared", "(x + 3) squared"],
            "correct_index": 0,
            "explanation": "This is a difference of squares: a^2 - b^2 = (a - b)(a + b), with a = x and b = 3.",
        },
        {
            "question_text": "The product of (x + 2) and (x + 3) is:",
            "options": ["x squared + 5x + 6", "x squared + 6x + 5", "x squared + 5x + 5", "x squared + x + 6"],
            "correct_index": 0,
            "explanation": "Expanding (x+2)(x+3) gives x^2 + 3x + 2x + 6 = x^2 + 5x + 6.",
        },
        {
            "question_text": "The area of a trapezium with parallel sides 10 cm and 14 cm, and height 6 cm, is:",
            "options": ["60 cm squared", "72 cm squared", "84 cm squared", "96 cm squared"],
            "correct_index": 1,
            "explanation": "Area = 1/2 x (sum of parallel sides) x height = 1/2 x 24 x 6 = 72 cm squared.",
        },
        {
            "question_text": "Which of these is a rational number between 1 and 2?",
            "options": ["1/2", "3/2", "5/2", "0"],
            "correct_index": 1,
            "explanation": "3/2 equals 1.5, which lies strictly between 1 and 2.",
        },
        {
            "question_text": "If x varies directly as y, and x = 10 when y = 2, find x when y = 5.",
            "options": ["20", "25", "15", "30"],
            "correct_index": 1,
            "explanation": "The constant of proportionality is x/y = 5, so when y = 5, x = 5 x 5 = 25.",
        },
        {
            "question_text": "If 8 workers can build a wall in 10 days, how many days will 4 workers take, working at the same rate?",
            "options": ["5", "15", "20", "40"],
            "correct_index": 2,
            "explanation": "Total work = 8 x 10 = 80 worker-days; with 4 workers, days needed = 80/4 = 20.",
        },
        {
            "question_text": "A regular polygon has each exterior angle equal to 40°. How many sides does it have?",
            "options": ["8", "9", "10", "12"],
            "correct_index": 1,
            "explanation": "The number of sides equals 360° divided by the exterior angle: 360/40 = 9.",
        },
        {
            "question_text": "Which of the following is not a perfect square?",
            "options": ["36", "49", "56", "64"],
            "correct_index": 2,
            "explanation": "56 lies between 7 squared (49) and 8 squared (64), so it is not a perfect square.",
        },
        {
            "question_text": "Simplify: (-3) to the power 3.",
            "options": ["-9", "9", "-27", "27"],
            "correct_index": 2,
            "explanation": "(-3) x (-3) x (-3) = 9 x (-3) = -27.",
        },
        {
            "question_text": "On a graph, the point (0, 0) is called the:",
            "options": ["Origin", "Axis", "Quadrant", "Coordinate"],
            "correct_index": 0,
            "explanation": "The point where the x-axis and y-axis intersect, (0, 0), is called the origin.",
        },
        {
            "question_text": "The cube root of 216 is:",
            "options": ["4", "5", "6", "7"],
            "correct_index": 2,
            "explanation": "6 x 6 x 6 = 216, so the cube root of 216 is 6.",
        },
        {
            "question_text": "Solve: 2(x + 3) = 16.",
            "options": ["4", "5", "6", "7"],
            "correct_index": 1,
            "explanation": "Expanding gives 2x + 6 = 16, so 2x = 10 and x = 5.",
        },
    ],
    "Science": [
        {
            "question_text": "Which method sows seeds evenly at a fixed depth using a machine, and prevents damage from birds?",
            "options": ["Broadcasting", "Seed drill", "Transplanting", "Hydroponics"],
            "correct_index": 1,
            "explanation": "A seed drill deposits seeds uniformly at a proper depth and covers them with soil.",
        },
        {
            "question_text": "Microorganisms commonly used to convert milk into curd are:",
            "options": ["Bacteria", "Viruses", "Protozoa", "Algae"],
            "correct_index": 0,
            "explanation": "Lactobacillus, a type of bacteria, converts milk into curd through fermentation.",
        },
        {
            "question_text": "Which of these is a synthetic fibre?",
            "options": ["Cotton", "Wool", "Nylon", "Silk"],
            "correct_index": 2,
            "explanation": "Nylon is manufactured from chemical raw materials, unlike the natural fibres cotton, wool, and silk.",
        },
        {
            "question_text": "Metals are generally good conductors of:",
            "options": ["Heat only", "Electricity only", "Both heat and electricity", "Neither heat nor electricity"],
            "correct_index": 2,
            "explanation": "Metals allow both heat and electric current to pass through them easily due to free electrons.",
        },
        {
            "question_text": "Coal and petroleum are examples of:",
            "options": ["Renewable resources", "Fossil fuels", "Metals", "Alloys"],
            "correct_index": 1,
            "explanation": "Coal and petroleum formed from buried organic matter over millions of years, making them fossil fuels.",
        },
        {
            "question_text": "In a candle flame, the innermost zone is:",
            "options": ["Blue and the hottest", "Dark and the least hot", "Bright yellow and luminous", "The outermost visible zone"],
            "correct_index": 1,
            "explanation": "The innermost zone contains unburnt wax vapour and is the least hot part of the flame.",
        },
        {
            "question_text": "The scientific name used to identify the tiger for conservation purposes is:",
            "options": ["Panthera tigris", "Panthera leo", "Felis catus", "Panthera pardus"],
            "correct_index": 0,
            "explanation": "Panthera tigris is the scientific (binomial) name of the tiger.",
        },
        {
            "question_text": "The basic structural and functional unit of life is the:",
            "options": ["Tissue", "Cell", "Organ", "Organism"],
            "correct_index": 1,
            "explanation": "The cell is the smallest unit that can perform all basic life functions.",
        },
        {
            "question_text": "In animals such as the hen, the embryo develops:",
            "options": ["Inside the mother's body (viviparous)", "Outside, in an egg (oviparous)", "Both inside and outside the body", "It does not develop from an embryo"],
            "correct_index": 1,
            "explanation": "Hens lay eggs, and the embryo develops outside the mother's body, making them oviparous.",
        },
        {
            "question_text": "The force that opposes relative motion between two surfaces in contact is:",
            "options": ["Gravity", "Friction", "Magnetism", "Tension"],
            "correct_index": 1,
            "explanation": "Friction acts opposite to the direction of relative motion between two touching surfaces.",
        },
        {
            "question_text": "Sound is produced due to:",
            "options": ["Vibration of an object", "Heating of an object", "Cooling of an object", "Static charge on an object"],
            "correct_index": 0,
            "explanation": "Sound is a form of energy produced when an object vibrates, disturbing the surrounding medium.",
        },
        {
            "question_text": "Electroplating works based on the:",
            "options": ["Heating effect of current", "Chemical effect of current", "Magnetic effect of current", "Optical effect of current"],
            "correct_index": 1,
            "explanation": "Electroplating uses the chemical effect of an electric current to deposit a metal layer on an object.",
        },
        {
            "question_text": "A ray of light that falls on a mirror's surface is called the:",
            "options": ["Reflected ray", "Incident ray", "Normal", "Refracted ray"],
            "correct_index": 1,
            "explanation": "The ray that strikes the mirror before bouncing back is called the incident ray.",
        },
        {
            "question_text": "A group of stars that appears to form a recognisable pattern in the sky is called a:",
            "options": ["Galaxy", "Constellation", "Asteroid belt", "Nebula"],
            "correct_index": 1,
            "explanation": "A constellation is a group of stars that, viewed from Earth, seems to form a pattern.",
        },
        {
            "question_text": "The mixing of harmful substances into air, water, or soil is called:",
            "options": ["Conservation", "Pollution", "Purification", "Composting"],
            "correct_index": 1,
            "explanation": "Pollution is the introduction of harmful substances into the environment.",
        },
        {
            "question_text": "Which gas present in air is essential for combustion?",
            "options": ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"],
            "correct_index": 1,
            "explanation": "Oxygen supports combustion; a substance burns only in the presence of oxygen.",
        },
        {
            "question_text": "Kharif crops such as paddy and maize are typically sown in the:",
            "options": ["Winter season", "Rainy (monsoon) season", "Peak summer", "Spring season"],
            "correct_index": 1,
            "explanation": "Kharif crops are sown at the start of the monsoon and harvested at its end.",
        },
        {
            "question_text": "The process by which plants lose water in vapour form through their leaves is called:",
            "options": ["Respiration", "Transpiration", "Photosynthesis", "Excretion"],
            "correct_index": 1,
            "explanation": "Transpiration is the loss of water vapour from plant surfaces, mainly through leaf stomata.",
        },
        {
            "question_text": "Rust forms on iron mainly due to a reaction with:",
            "options": ["Oxygen and moisture", "Nitrogen", "Carbon dioxide only", "Hydrogen"],
            "correct_index": 0,
            "explanation": "Iron reacts with oxygen in the presence of moisture to form iron oxide, or rust.",
        },
        {
            "question_text": "The change of a substance directly from solid to gas, without passing through the liquid state, is called:",
            "options": ["Evaporation", "Sublimation", "Condensation", "Melting"],
            "correct_index": 1,
            "explanation": "Sublimation is the direct transition of a substance from solid to gaseous state.",
        },
    ],
    "English": [
        {
            "question_text": "Choose the correct passive voice of: 'The teacher is teaching the students.'",
            "options": [
                "The students is taught by the teacher.",
                "The students are being taught by the teacher.",
                "The students were taught by the teacher.",
                "The students taught the teacher.",
            ],
            "correct_index": 1,
            "explanation": "The present continuous active voice becomes 'is/are being + past participle' in the passive.",
        },
        {
            "question_text": "Choose the correct reported speech for: He said, 'I am going to the market.'",
            "options": [
                "He said that he was going to the market.",
                "He said that he is going to the market.",
                "He said that he will go to the market.",
                "He told that I am going to the market.",
            ],
            "correct_index": 0,
            "explanation": "In reported speech, present continuous ('am going') shifts to past continuous ('was going').",
        },
        {
            "question_text": "Identify the modal verb in the sentence: 'You must complete your homework.'",
            "options": ["must", "complete", "your", "homework"],
            "correct_index": 0,
            "explanation": "'Must' expresses necessity and is a modal auxiliary verb.",
        },
        {
            "question_text": "Choose the correctly punctuated sentence.",
            "options": ["Where are you going.", "Where are you going?", "where are you going?", "Where, are you going?"],
            "correct_index": 1,
            "explanation": "A question must end with a question mark, and the first word must be capitalised.",
        },
        {
            "question_text": "Select the correctly formed conditional sentence.",
            "options": [
                "If it rains, I stayed home.",
                "If it rains, I will stay home.",
                "If it rain, I will stay home.",
                "If it rains, I stay at home tomorrow.",
            ],
            "correct_index": 1,
            "explanation": "A first conditional pairs present simple in the if-clause with will + base verb in the main clause.",
        },
        {
            "question_text": "Choose the word closest in meaning to 'abundant'.",
            "options": ["Scarce", "Plentiful", "Empty", "Fragile"],
            "correct_index": 1,
            "explanation": "'Abundant' means existing in large quantities, which matches 'plentiful'.",
        },
        {
            "question_text": "Choose the antonym of 'diligent'.",
            "options": ["Hardworking", "Lazy", "Careful", "Sincere"],
            "correct_index": 1,
            "explanation": "'Diligent' means hardworking and careful; its opposite is 'lazy'.",
        },
        {
            "question_text": "Fill in the blank with the correct connector: 'She stayed home ___ she was unwell.'",
            "options": ["although", "because", "unless", "after"],
            "correct_index": 1,
            "explanation": "'Because' correctly introduces the reason she stayed home.",
        },
        {
            "question_text": "Identify the noun clause in: 'What she said surprised everyone.'",
            "options": ["What she said", "surprised", "everyone", "she said"],
            "correct_index": 0,
            "explanation": "'What she said' functions as the subject of the sentence, making it a noun clause.",
        },
        {
            "question_text": "Choose the grammatically correct sentence.",
            "options": [
                "Neither of the boys were present.",
                "Neither of the boys was present.",
                "Neither of the boy was present.",
                "Neither of boys was present.",
            ],
            "correct_index": 1,
            "explanation": "'Neither' is singular and takes a singular verb, 'was'.",
        },
        {
            "question_text": "Choose the correct form: 'He ___ to school every day.'",
            "options": ["go", "goes", "going", "gone"],
            "correct_index": 1,
            "explanation": "Third-person singular subjects take the -s form in present simple: 'He goes'.",
        },
        {
            "question_text": "Identify the adjective in the sentence: 'The bright student answered quickly.'",
            "options": ["Bright", "Student", "Answered", "Quickly"],
            "correct_index": 0,
            "explanation": "'Bright' describes the noun 'student', making it an adjective.",
        },
        {
            "question_text": "Choose the correct preposition: 'The book is ___ the table.'",
            "options": ["in", "on", "at", "by"],
            "correct_index": 1,
            "explanation": "'On' correctly shows the book resting on the surface of the table.",
        },
        {
            "question_text": "Which sentence uses the correct article?",
            "options": [
                "I saw an unicorn.",
                "I saw a unicorn.",
                "I saw the unicorn is nice.",
                "I saw unicorn.",
            ],
            "correct_index": 1,
            "explanation": "'Unicorn' begins with a consonant sound, so it takes the article 'a', not 'an'.",
        },
        {
            "question_text": "Choose the correct plural form of 'child'.",
            "options": ["Childs", "Children", "Childes", "Childrens"],
            "correct_index": 1,
            "explanation": "'Child' has the irregular plural form 'children'.",
        },
        {
            "question_text": "Choose the correctly spelled word.",
            "options": ["Recieve", "Receive", "Receeve", "Receve"],
            "correct_index": 1,
            "explanation": "The correct spelling follows 'i before e except after c': 'receive'.",
        },
        {
            "question_text": "Choose the correct comparative form: 'This box is ___ than that one.'",
            "options": ["heavy", "heavier", "heaviest", "more heavy"],
            "correct_index": 1,
            "explanation": "Comparing two things uses the comparative form, formed here by adding '-er': 'heavier'.",
        },
        {
            "question_text": "Choose the correct superlative form: 'Everest is the ___ mountain in the world.'",
            "options": ["high", "higher", "highest", "most high"],
            "correct_index": 2,
            "explanation": "Comparing among more than two things uses the superlative form: 'highest'.",
        },
        {
            "question_text": "Identify the correctly formed question tag: 'You are coming, ___?'",
            "options": ["isn't it", "aren't you", "don't you", "won't you"],
            "correct_index": 1,
            "explanation": "A question tag reverses the auxiliary and matches the subject: 'are' becomes 'aren't you'.",
        },
        {
            "question_text": "Choose the sentence that correctly uses 'for' with a duration of time.",
            "options": [
                "I have lived here since five years.",
                "I have lived here for five years.",
                "I have lived here since 2018 for now.",
                "I have lived here for 2018.",
            ],
            "correct_index": 1,
            "explanation": "'For' is used with a duration (five years); 'since' is used with a starting point in time.",
        },
    ],
    "Hindi": [
        {
            "question_text": "'राजपुत्र' शब्द में कौन सा समास है?",
            "options": ["तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास", "अव्ययीभाव समास"],
            "correct_index": 0,
            "explanation": "'राजा का पुत्र' का संक्षिप्त रूप होने के कारण यह तत्पुरुष समास है।",
        },
        {
            "question_text": "'विद्यालय' शब्द का सही संधि-विच्छेद है:",
            "options": ["विद्या + आलय", "विद्य + आलय", "विद्या + लय", "विद् + आलय"],
            "correct_index": 0,
            "explanation": "'विद्या' और 'आलय' के मेल से दीर्घ संधि द्वारा 'विद्यालय' शब्द बनता है।",
        },
        {
            "question_text": "'नीलकमल' में कौन सा समास है?",
            "options": ["कर्मधारय समास", "द्वंद्व समास", "तत्पुरुष समास", "बहुव्रीहि समास"],
            "correct_index": 0,
            "explanation": "विशेषण-विशेष्य के मेल ('नीला कमल') के कारण यह कर्मधारय समास है।",
        },
        {
            "question_text": "'अंधों में काना राजा' लोकोक्ति का अर्थ है:",
            "options": [
                "सबसे श्रेष्ठ व्यक्ति का सम्मान होना",
                "मूर्खों में थोड़ा समझदार व्यक्ति भी प्रधान बन जाता है",
                "अंधा व्यक्ति सचमुच राजा बन गया",
                "इसका कोई विशेष अर्थ नहीं है",
            ],
            "correct_index": 1,
            "explanation": "यह लोकोक्ति बताती है कि योग्य लोगों की अनुपस्थिति में साधारण व्यक्ति भी प्रधान बन जाता है।",
        },
        {
            "question_text": "'नाक में दम करना' मुहावरे का अर्थ है:",
            "options": ["बहुत परेशान करना", "खुश होना", "सो जाना", "चुप रहना"],
            "correct_index": 0,
            "explanation": "इस मुहावरे का प्रयोग किसी को अत्यधिक तंग या परेशान करने के अर्थ में होता है।",
        },
        {
            "question_text": "'हाथ' शब्द का अनेकार्थी अर्थ नहीं है:",
            "options": ["शक्ति", "सहायता", "आँख", "स्वामित्व/अधिकार"],
            "correct_index": 2,
            "explanation": "'हाथ' के अनेक अर्थ शक्ति, सहायता और अधिकार से जुड़े हैं, परंतु 'आँख' इसका अर्थ नहीं है।",
        },
        {
            "question_text": "'अलंकार' किसे कहते हैं?",
            "options": ["भाषा को सजाने वाले काव्य-तत्व", "व्याकरण के नियम", "वाक्य के भेद", "शब्दों की वर्तनी"],
            "correct_index": 0,
            "explanation": "अलंकार वे तत्व हैं जो काव्य की भाषा को सुंदर और प्रभावशाली बनाते हैं।",
        },
        {
            "question_text": "जहाँ उपमेय की तुलना उपमान से 'सा', 'सी', 'जैसा' जैसे शब्दों द्वारा की जाए, वहाँ कौन सा अलंकार होता है?",
            "options": ["उपमा अलंकार", "रूपक अलंकार", "अनुप्रास अलंकार", "यमक अलंकार"],
            "correct_index": 0,
            "explanation": "दो वस्तुओं के बीच समानता दर्शाने के लिए तुलनात्मक शब्दों का प्रयोग उपमा अलंकार कहलाता है।",
        },
        {
            "question_text": "जब वाक्य में एक ही वर्ण की आवृत्ति बार-बार हो, वहाँ कौन सा अलंकार होता है?",
            "options": ["अनुप्रास अलंकार", "उपमा अलंकार", "उत्प्रेक्षा अलंकार", "यमक अलंकार"],
            "correct_index": 0,
            "explanation": "एक ही वर्ण की बार-बार आवृत्ति होने पर अनुप्रास अलंकार होता है।",
        },
        {
            "question_text": "निम्न में से शुद्ध वाक्य चुनिए:",
            "options": ["वह घर जा रहा है।", "वह घर को जा रहा है।", "वह घर जा रहे है।", "वह घर जा रहा हूँ।"],
            "correct_index": 0,
            "explanation": "कर्ता, क्रिया और वचन का सही मेल होने के कारण पहला वाक्य ही शुद्ध है।",
        },
        {
            "question_text": "'दूध का दूध, पानी का पानी' लोकोक्ति का अर्थ है:",
            "options": ["उचित न्याय करना", "झूठ बोलना", "दूध और पानी बाँटना", "पानी बचाना"],
            "correct_index": 0,
            "explanation": "यह लोकोक्ति सही-गलत का स्पष्ट और निष्पक्ष न्याय करने के अर्थ में प्रयुक्त होती है।",
        },
        {
            "question_text": "'गाय' का पर्यायवाची शब्द है:",
            "options": ["गौ", "घोड़ा", "बकरी", "हिरण"],
            "correct_index": 0,
            "explanation": "'गौ' गाय का ही पर्यायवाची (समानार्थी) शब्द है।",
        },
        {
            "question_text": "'दिन' का विलोम शब्द है:",
            "options": ["रात", "प्रकाश", "सुबह", "शाम"],
            "correct_index": 0,
            "explanation": "'दिन' का सीधा विपरीत अर्थ देने वाला शब्द 'रात' है।",
        },
        {
            "question_text": "'सूर्य' का पर्यायवाची शब्द नहीं है:",
            "options": ["भानु", "रवि", "दिनकर", "चंद्र"],
            "correct_index": 3,
            "explanation": "'चंद्र' चाँद का पर्यायवाची है, सूर्य का नहीं; बाकी तीनों सूर्य के ही पर्यायवाची हैं।",
        },
        {
            "question_text": "समास के सामान्यतः कितने भेद माने गए हैं?",
            "options": ["चार", "पाँच", "छह", "तीन"],
            "correct_index": 2,
            "explanation": "समास के छह भेद माने जाते हैं: तत्पुरुष, कर्मधारय, द्विगु, द्वंद्व, बहुव्रीहि और अव्ययीभाव।",
        },
        {
            "question_text": "'चरण' शब्द का एक अनेकार्थी अर्थ है:",
            "options": ["पैर", "कविता का एक भाग (छंद-चरण)", "दोनों अर्थ सही हैं", "इनमें से कोई नहीं"],
            "correct_index": 2,
            "explanation": "'चरण' शब्द के 'पैर' और 'कविता के भाग' दोनों ही मान्य अर्थ हैं।",
        },
        {
            "question_text": "'सूर्योदय' शब्द का सही संधि-विच्छेद है:",
            "options": ["सूर्य + उदय", "सूर्यो + दय", "सूर + योदय", "सूर्य + ओदय"],
            "correct_index": 0,
            "explanation": "'सूर्य' और 'उदय' के मेल से गुण संधि द्वारा 'सूर्योदय' शब्द बनता है।",
        },
        {
            "question_text": "'यमक अलंकार' में क्या होता है?",
            "options": [
                "एक ही शब्द का बार-बार भिन्न-भिन्न अर्थों में प्रयोग",
                "दो वस्तुओं की तुलना",
                "वर्णों की बार-बार आवृत्ति",
                "अतिशयोक्तिपूर्ण वर्णन",
            ],
            "correct_index": 0,
            "explanation": "यमक अलंकार में एक ही शब्द की आवृत्ति होती है, पर हर बार उसका अर्थ भिन्न होता है।",
        },
        {
            "question_text": "'रात-दिन' शब्द में कौन सा समास है?",
            "options": ["द्वंद्व समास", "तत्पुरुष समास", "कर्मधारय समास", "बहुव्रीहि समास"],
            "correct_index": 0,
            "explanation": "दो विपरीत या सहयोगी पदों के योग ('रात और दिन') से बना यह द्वंद्व समास है।",
        },
        {
            "question_text": "'अंधेर नगरी चौपट राजा' लोकोक्ति किस ओर संकेत करती है?",
            "options": ["कुशासन और अव्यवस्था", "अच्छे शासन की ओर", "समृद्ध नगर की ओर", "शांतिपूर्ण राज्य की ओर"],
            "correct_index": 0,
            "explanation": "यह लोकोक्ति बिना सोचे-समझे चलने वाले कुशासन और अव्यवस्था की स्थिति को दर्शाती है।",
        },
    ],
    "Social Science": [
        {
            "question_text": "The Battle of Plassey, which marked the beginning of British political control in India, was fought in:",
            "options": ["1757", "1764", "1857", "1600"],
            "correct_index": 0,
            "explanation": "The Battle of Plassey in 1757 established the East India Company's control over Bengal.",
        },
        {
            "question_text": "The Governor-General of India during the revolt of 1857 was:",
            "options": ["Lord Dalhousie", "Lord Canning", "Lord Curzon", "Warren Hastings"],
            "correct_index": 1,
            "explanation": "Lord Canning was the Governor-General of India when the 1857 revolt broke out.",
        },
        {
            "question_text": "The policy that allowed the British to annex Indian states if a ruler died without a natural heir was called the:",
            "options": ["Subsidiary Alliance", "Doctrine of Lapse", "Permanent Settlement", "Ryotwari System"],
            "correct_index": 1,
            "explanation": "Under the Doctrine of Lapse, the British annexed states lacking a natural male heir.",
        },
        {
            "question_text": "The revolt of 1857 first broke out at:",
            "options": ["Meerut", "Delhi", "Kanpur", "Lucknow"],
            "correct_index": 0,
            "explanation": "The uprising began among sepoys at Meerut before spreading to Delhi and elsewhere.",
        },
        {
            "question_text": "Raja Ram Mohan Roy is best remembered for his efforts towards:",
            "options": ["Abolishing the practice of sati", "Strengthening British rule", "Founding the Indian National Congress", "Promoting industrial growth"],
            "correct_index": 0,
            "explanation": "Raja Ram Mohan Roy campaigned against sati, leading to its ban in 1829.",
        },
        {
            "question_text": "Which 19th-century reform movements worked against child marriage and for widow remarriage?",
            "options": ["Only the Brahmo Samaj", "Only the Arya Samaj", "Both the Brahmo Samaj and the Arya Samaj", "Neither of them"],
            "correct_index": 2,
            "explanation": "Both the Brahmo Samaj and the Arya Samaj campaigned for social reforms including widow remarriage.",
        },
        {
            "question_text": "A resource that nature can replenish in a relatively short time is called a:",
            "options": ["Non-renewable resource", "Renewable resource", "Human resource", "Abiotic resource"],
            "correct_index": 1,
            "explanation": "Renewable resources, like water and forests, can be naturally replenished over time.",
        },
        {
            "question_text": "Which of these is an example of a non-renewable resource?",
            "options": ["Solar energy", "Wind energy", "Coal", "Forest"],
            "correct_index": 2,
            "explanation": "Coal took millions of years to form and cannot be replenished within a human lifetime.",
        },
        {
            "question_text": "The practice of growing a single crop repeatedly over a large area is called:",
            "options": ["Mixed farming", "Monoculture", "Shifting cultivation", "Crop rotation"],
            "correct_index": 1,
            "explanation": "Monoculture refers to cultivating only one crop species on a piece of land.",
        },
        {
            "question_text": "Industries that use minerals as their main raw material, such as iron and steel plants, are classified as:",
            "options": ["Agro-based industries", "Mineral-based industries", "Marine-based industries", "Forest-based industries"],
            "correct_index": 1,
            "explanation": "Mineral-based industries use minerals extracted from the earth as their primary raw material.",
        },
        {
            "question_text": "The skill, education, and effort of people that contributes to production is called:",
            "options": ["Natural resource", "Human resource", "Physical capital", "Land resource"],
            "correct_index": 1,
            "explanation": "People, with their skills and labour, form the human resource that drives production.",
        },
        {
            "question_text": "The Indian Constitution came into effect on:",
            "options": ["15 August 1947", "26 January 1950", "26 November 1949", "2 October 1950"],
            "correct_index": 1,
            "explanation": "The Constitution of India came into force on 26 January 1950, celebrated as Republic Day.",
        },
        {
            "question_text": "The Preamble to the Indian Constitution describes India as a:",
            "options": ["Monarchy", "Sovereign Socialist Secular Democratic Republic", "Unitary state only", "British colony"],
            "correct_index": 1,
            "explanation": "The Preamble declares India to be a Sovereign, Socialist, Secular, Democratic Republic.",
        },
        {
            "question_text": "In the Indian context, secularism means that the state:",
            "options": ["Has one official religion", "Treats all religions equally and favours none", "Bans the practice of all religions", "Allows only one community to hold office"],
            "correct_index": 1,
            "explanation": "Indian secularism means the state maintains equal distance from, and does not favour, any religion.",
        },
        {
            "question_text": "The law-making body of the Indian government at the national level is called the:",
            "options": ["Supreme Court", "Parliament", "Election Commission", "Cabinet Secretariat"],
            "correct_index": 1,
            "explanation": "Parliament is the national legislative body responsible for making laws in India.",
        },
        {
            "question_text": "The Indian Parliament consists of the President, the Lok Sabha, and the:",
            "options": ["Vidhan Sabha", "Rajya Sabha", "Municipal Corporation", "Gram Panchayat"],
            "correct_index": 1,
            "explanation": "Parliament comprises the President, the Lok Sabha (lower house), and the Rajya Sabha (upper house).",
        },
        {
            "question_text": "The highest court in India, which also has the power of judicial review, is the:",
            "options": ["High Court", "District Court", "Supreme Court", "Sessions Court"],
            "correct_index": 2,
            "explanation": "The Supreme Court is the apex judicial body and can review laws against the Constitution.",
        },
        {
            "question_text": "Members of the Lok Sabha are elected by the people for a term of:",
            "options": ["4 years", "5 years", "6 years", "7 years"],
            "correct_index": 1,
            "explanation": "The Lok Sabha has a normal term of 5 years unless dissolved earlier.",
        },
        {
            "question_text": "The practice where tribal groups cleared forest patches to grow crops for a season before moving on was called:",
            "options": ["Jhum cultivation", "Ryotwari system", "Zamindari system", "Permanent Settlement"],
            "correct_index": 0,
            "explanation": "Jhum, or shifting cultivation, involved clearing and farming forest patches before moving to new land.",
        },
        {
            "question_text": "The arrangement under which the British collected a fixed land revenue from Bengal zamindars was called the:",
            "options": ["Permanent Settlement", "Doctrine of Lapse", "Government of India Act", "Charter Act"],
            "correct_index": 0,
            "explanation": "The Permanent Settlement of 1793 fixed the land revenue zamindars had to pay to the British.",
        },
    ],
}
