QUESTIONS: dict[str, list[dict]] = {
    "Mathematics": [
        {
            "question_text": "Which of the following numbers is irrational?",
            "options": ["√4", "√9", "√2", "22/7"],
            "correct_index": 2,
            "explanation": "√2 cannot be expressed as p/q, so it is irrational, unlike √4 = 2 and √9 = 3.",
        },
        {
            "question_text": "The decimal expansion of a rational number is always",
            "options": [
                "Non-terminating non-recurring",
                "Terminating or non-terminating recurring",
                "Always terminating",
                "Always non-terminating",
            ],
            "correct_index": 1,
            "explanation": "Rational numbers have decimal expansions that either terminate or repeat (recur).",
        },
        {
            "question_text": "Simplify: (2 + √3)(2 - √3)",
            "options": ["1", "4", "7", "-1"],
            "correct_index": 0,
            "explanation": "Using (a+b)(a-b) = a² - b²: 2² - (√3)² = 4 - 3 = 1.",
        },
        {
            "question_text": "What is the degree of the polynomial 4x³ - 3x² + 7x - 2?",
            "options": ["2", "3", "4", "1"],
            "correct_index": 1,
            "explanation": "The degree of a polynomial is the highest power of x, which is 3.",
        },
        {
            "question_text": "If p(x) = x² - 5x + 6, find p(2).",
            "options": ["0", "2", "-2", "6"],
            "correct_index": 0,
            "explanation": "Substituting x = 2: 4 - 10 + 6 = 0, so x = 2 is a zero of the polynomial.",
        },
        {
            "question_text": "Factorise: x² - 9",
            "options": ["(x-3)(x-3)", "(x+3)(x+3)", "(x-3)(x+3)", "x(x-9)"],
            "correct_index": 2,
            "explanation": "This is a difference of squares: x² - 9 = (x-3)(x+3).",
        },
        {
            "question_text": "In which quadrant does the point (-3, 4) lie?",
            "options": ["I", "II", "III", "IV"],
            "correct_index": 1,
            "explanation": "A point with negative x and positive y lies in the second quadrant.",
        },
        {
            "question_text": "The point (0, 0) is called the",
            "options": ["Abscissa", "Ordinate", "Origin", "Quadrant"],
            "correct_index": 2,
            "explanation": "The point where the x-axis and y-axis intersect is called the origin.",
        },
        {
            "question_text": "How many solutions does the linear equation 2x + 3y = 6 have?",
            "options": ["Exactly one", "Exactly two", "Infinitely many", "No solution"],
            "correct_index": 2,
            "explanation": "A linear equation in two variables has infinitely many solutions, each a point on its graph line.",
        },
        {
            "question_text": "According to Euclid's first postulate, a straight line may be drawn from",
            "options": [
                "Any point to infinity",
                "Any one point to any other point",
                "A point to itself",
                "Two parallel lines",
            ],
            "correct_index": 1,
            "explanation": "Euclid's first postulate states a straight line can be drawn from any one point to any other point.",
        },
        {
            "question_text": "If two lines intersect, the vertically opposite angles are",
            "options": ["Complementary", "Supplementary", "Equal", "Unequal"],
            "correct_index": 2,
            "explanation": "Vertically opposite angles formed by two intersecting lines are always equal.",
        },
        {
            "question_text": "The sum of the angles of a triangle is",
            "options": ["90°", "180°", "270°", "360°"],
            "correct_index": 1,
            "explanation": "By the angle sum property, the three interior angles of any triangle add up to 180°.",
        },
        {
            "question_text": "In an isosceles triangle, the angles opposite the equal sides are",
            "options": ["Equal", "Supplementary", "Complementary", "Unequal"],
            "correct_index": 0,
            "explanation": "In an isosceles triangle, the angles opposite the two equal sides are equal.",
        },
        {
            "question_text": "The diagonals of a parallelogram",
            "options": ["Are equal", "Bisect each other", "Are perpendicular", "Are parallel"],
            "correct_index": 1,
            "explanation": "A key property of a parallelogram is that its diagonals bisect each other.",
        },
        {
            "question_text": "A quadrilateral with all sides equal and all angles 90° is a",
            "options": ["Rhombus", "Rectangle", "Square", "Trapezium"],
            "correct_index": 2,
            "explanation": "A square has all four sides equal in length and all four angles equal to 90°.",
        },
        {
            "question_text": "Two triangles on the same base and between the same parallels are equal in",
            "options": ["Perimeter", "Area", "Angle", "Side length"],
            "correct_index": 1,
            "explanation": "Triangles on the same base and between the same parallels always have equal area.",
        },
        {
            "question_text": "The longest chord of a circle is its",
            "options": ["Radius", "Diameter", "Arc", "Sector"],
            "correct_index": 1,
            "explanation": "The diameter, which passes through the centre, is the longest possible chord of a circle.",
        },
        {
            "question_text": "Heron's formula computes the area of a triangle using",
            "options": ["Its height only", "Its three side lengths only", "Its base only", "Its angles only"],
            "correct_index": 1,
            "explanation": "Heron's formula finds a triangle's area purely from the lengths of its three sides.",
        },
        {
            "question_text": "Using Heron's formula, the area of a triangle with sides 3 cm, 4 cm and 5 cm is",
            "options": ["5 cm²", "6 cm²", "7 cm²", "12 cm²"],
            "correct_index": 1,
            "explanation": "s = (3+4+5)/2 = 6, so Area = √(6×3×2×1) = √36 = 6 cm².",
        },
        {
            "question_text": "The curved surface area of a cylinder of radius r and height h is",
            "options": ["πr²h", "2πrh", "2πr(r+h)", "πr(r+l)"],
            "correct_index": 1,
            "explanation": "The curved surface area of a right circular cylinder is given by 2πrh.",
        },
    ],
    "Science": [
        {
            "question_text": "Which state of matter has a definite volume but no definite shape?",
            "options": ["Solid", "Liquid", "Gas", "Plasma"],
            "correct_index": 1,
            "explanation": "Liquids have a fixed volume but take the shape of whatever container they are in.",
        },
        {
            "question_text": "The process by which a solid changes directly into a gas is called",
            "options": ["Evaporation", "Sublimation", "Condensation", "Melting"],
            "correct_index": 1,
            "explanation": "Sublimation is the direct change of a solid into vapour without passing through the liquid state.",
        },
        {
            "question_text": "A mixture of two miscible liquids that cannot be separated by filtration is usually separated by",
            "options": ["Sublimation", "Distillation", "Sieving", "Magnetic separation"],
            "correct_index": 1,
            "explanation": "Distillation separates miscible liquids based on differences in their boiling points.",
        },
        {
            "question_text": "Which of these is a pure substance?",
            "options": ["Air", "Soil", "Distilled water", "Milk"],
            "correct_index": 2,
            "explanation": "Distilled water is made of only H2O molecules, so it is a pure substance (a compound).",
        },
        {
            "question_text": "According to Dalton's atomic theory, atoms of the same element are",
            "options": [
                "Different in mass",
                "Identical in mass and properties",
                "Always radioactive",
                "Never combine with other atoms",
            ],
            "correct_index": 1,
            "explanation": "Dalton proposed that all atoms of a given element are identical in mass and chemical properties.",
        },
        {
            "question_text": "The chemical formula of water is",
            "options": ["H2O2", "HO2", "H2O", "H3O"],
            "correct_index": 2,
            "explanation": "A water molecule has two hydrogen atoms bonded to one oxygen atom: H2O.",
        },
        {
            "question_text": "Who discovered the electron?",
            "options": ["J.J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"],
            "correct_index": 0,
            "explanation": "J.J. Thomson discovered the electron in 1897 through his cathode ray experiments.",
        },
        {
            "question_text": "The number of protons in an atom is called its",
            "options": ["Mass number", "Atomic number", "Valency", "Isotope number"],
            "correct_index": 1,
            "explanation": "The atomic number of an element is defined as the number of protons in its nucleus.",
        },
        {
            "question_text": "Which cell organelle is known as the 'powerhouse of the cell'?",
            "options": ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"],
            "correct_index": 2,
            "explanation": "Mitochondria generate ATP through cellular respiration, earning them the name 'powerhouse of the cell'.",
        },
        {
            "question_text": "Which tissue is responsible for transporting water in plants?",
            "options": ["Phloem", "Xylem", "Epidermis", "Parenchyma"],
            "correct_index": 1,
            "explanation": "Xylem tissue conducts water and dissolved minerals from the roots to the rest of the plant.",
        },
        {
            "question_text": "Which kingdom includes prokaryotic organisms such as bacteria?",
            "options": ["Fungi", "Monera", "Protista", "Animalia"],
            "correct_index": 1,
            "explanation": "Kingdom Monera consists of prokaryotic organisms, including all bacteria.",
        },
        {
            "question_text": "An object moving with uniform velocity has",
            "options": [
                "Zero acceleration",
                "Increasing acceleration",
                "Constant non-zero acceleration",
                "Decreasing velocity",
            ],
            "correct_index": 0,
            "explanation": "Uniform velocity means speed and direction stay constant, so the acceleration is zero.",
        },
        {
            "question_text": "Newton's first law of motion is also known as the law of",
            "options": ["Gravitation", "Inertia", "Conservation of energy", "Action-reaction"],
            "correct_index": 1,
            "explanation": "Newton's first law describes inertia — a body's resistance to a change in its state of motion.",
        },
        {
            "question_text": "The SI unit of force is the",
            "options": ["Joule", "Watt", "Newton", "Pascal"],
            "correct_index": 2,
            "explanation": "Force is measured in newtons (N) in the SI system.",
        },
        {
            "question_text": "According to the universal law of gravitation, the gravitational force between two objects is",
            "options": [
                "Inversely proportional to the square of the distance between them",
                "Directly proportional to the square of the distance between them",
                "Independent of their masses",
                "Independent of the distance between them",
            ],
            "correct_index": 0,
            "explanation": "Gravitational force decreases with the square of the distance between the two masses (F ∝ 1/d²).",
        },
        {
            "question_text": "Work done by a force is zero when",
            "options": [
                "Force and displacement are in the same direction",
                "Force is perpendicular to displacement",
                "The force is very large",
                "The displacement is very large",
            ],
            "correct_index": 1,
            "explanation": "Work = F × d × cosθ; when force is perpendicular to displacement, θ = 90° and cosθ = 0, so work is zero.",
        },
        {
            "question_text": "Sound cannot travel through",
            "options": ["Solids", "Liquids", "Gases", "Vacuum"],
            "correct_index": 3,
            "explanation": "Sound is a mechanical wave that needs a medium to travel, so it cannot pass through a vacuum.",
        },
        {
            "question_text": "The disease that spreads through the bite of the female Anopheles mosquito is",
            "options": ["Dengue", "Malaria", "Typhoid", "Cholera"],
            "correct_index": 1,
            "explanation": "Malaria is caused by the Plasmodium parasite, transmitted by the bite of the female Anopheles mosquito.",
        },
        {
            "question_text": "Which of these is a renewable natural resource?",
            "options": ["Coal", "Petroleum", "Solar energy", "Natural gas"],
            "correct_index": 2,
            "explanation": "Solar energy is continuously replenished by the sun, making it a renewable resource.",
        },
        {
            "question_text": "Improving crop yield by cross-breeding different genetic varieties is called",
            "options": ["Crop rotation", "Crop variety improvement", "Intercropping", "Weeding"],
            "correct_index": 1,
            "explanation": "Crop variety improvement uses hybridisation and cross-breeding to develop higher-yielding varieties.",
        },
    ],
    "English": [
        {
            "question_text": "Choose the correct form: She ____ to school every day.",
            "options": ["go", "goes", "going", "gone"],
            "correct_index": 1,
            "explanation": "With a third-person singular subject in the simple present, the verb takes an 's': 'goes'.",
        },
        {
            "question_text": "Identify the tense: 'They had finished the project before the deadline.'",
            "options": ["Simple past", "Past continuous", "Past perfect", "Present perfect"],
            "correct_index": 2,
            "explanation": "'had + past participle' (had finished) is the past perfect tense, showing completion before another past event.",
        },
        {
            "question_text": "Change to passive voice: 'The chef cooks the meal.'",
            "options": [
                "The meal is cooked by the chef.",
                "The meal was cooked by the chef.",
                "The meal cooks by the chef.",
                "The chef is cooked by the meal.",
            ],
            "correct_index": 0,
            "explanation": "Simple present active becomes 'is/are + past participle' in the passive voice.",
        },
        {
            "question_text": "Choose the correctly punctuated sentence.",
            "options": [
                "Where are you going",
                "Where are you going?",
                "where are you going?",
                "Where are you going.",
            ],
            "correct_index": 1,
            "explanation": "A question must begin with a capital letter and end with a question mark.",
        },
        {
            "question_text": "Fill in the blank with the correct article: 'She is ___ honest woman.'",
            "options": ["a", "an", "the", "no article"],
            "correct_index": 1,
            "explanation": "'Honest' begins with a vowel sound, so it takes the article 'an'.",
        },
        {
            "question_text": "Identify the modal verb in: 'You must submit the assignment on time.'",
            "options": ["submit", "must", "assignment", "time"],
            "correct_index": 1,
            "explanation": "'Must' expresses necessity or obligation and is the modal verb in this sentence.",
        },
        {
            "question_text": "Choose the sentence with correct subject-verb agreement.",
            "options": [
                "The list of items are on the table.",
                "The list of items is on the table.",
                "The list of items were on the table.",
                "The list of items being on the table.",
            ],
            "correct_index": 1,
            "explanation": "The subject is 'list' (singular), so it takes the singular verb 'is', regardless of 'items'.",
        },
        {
            "question_text": "Convert to indirect speech: He said, 'I am tired.'",
            "options": [
                "He said that he is tired.",
                "He said that he was tired.",
                "He says that he was tired.",
                "He said that I was tired.",
            ],
            "correct_index": 1,
            "explanation": "In reported speech, present tense 'am' shifts back to past tense 'was', and 'I' becomes 'he'.",
        },
        {
            "question_text": "Identify the type of clause: 'Although it was raining, we went out.'",
            "options": ["Main clause", "Noun clause", "Subordinate (adverbial) clause", "Relative clause"],
            "correct_index": 2,
            "explanation": "'Although it was raining' is a subordinate clause of contrast, functioning as an adverbial clause.",
        },
        {
            "question_text": "Choose the correct preposition: 'The book is ___ the table.'",
            "options": ["in", "on", "at", "by"],
            "correct_index": 1,
            "explanation": "'On' is the correct preposition for something resting on a flat surface.",
        },
        {
            "question_text": "Choose the antonym of 'generous'.",
            "options": ["Kind", "Stingy", "Wealthy", "Friendly"],
            "correct_index": 1,
            "explanation": "'Stingy' means unwilling to give or share, the opposite of 'generous'.",
        },
        {
            "question_text": "Choose the synonym of 'enormous'.",
            "options": ["Tiny", "Huge", "Narrow", "Weak"],
            "correct_index": 1,
            "explanation": "'Huge' means very large, matching the meaning of 'enormous'.",
        },
        {
            "question_text": "Identify the grammatical error: 'Each of the boys have submitted their homework.'",
            "options": ["Each", "of the boys", "have", "their"],
            "correct_index": 2,
            "explanation": "'Each' is a singular subject, so the verb should be 'has', not 'have'.",
        },
        {
            "question_text": "Choose the correctly spelled word.",
            "options": ["Recieve", "Receive", "Receeve", "Receve"],
            "correct_index": 1,
            "explanation": "The correct spelling follows the 'i before e except after c' rule: 'Receive'.",
        },
        {
            "question_text": "Choose the correct plural of 'child'.",
            "options": ["Childs", "Childes", "Children", "Childrens"],
            "correct_index": 2,
            "explanation": "'Child' has an irregular plural form: 'children'.",
        },
        {
            "question_text": "Identify the part of speech of the underlined idea: 'She sings beautifully.'",
            "options": ["Noun", "Adjective", "Adverb", "Pronoun"],
            "correct_index": 2,
            "explanation": "'Beautifully' describes how she sings, making it an adverb.",
        },
        {
            "question_text": "Choose the correct conditional form: 'If it rains, ___.'",
            "options": ["we will stay home", "we would stay home", "we stayed home", "we staying home"],
            "correct_index": 0,
            "explanation": "This is a first conditional (real future possibility): 'If + present simple, will + base verb'.",
        },
        {
            "question_text": "Choose the correct comparative form: 'This road is ___ than that one.'",
            "options": ["wide", "widest", "wider", "more wide"],
            "correct_index": 2,
            "explanation": "When comparing two things, the comparative form 'wider' is used.",
        },
        {
            "question_text": "Identify the direct object in: 'Riya wrote a letter.'",
            "options": ["Riya", "wrote", "a letter", "None"],
            "correct_index": 2,
            "explanation": "'A letter' receives the action of the verb 'wrote', making it the direct object.",
        },
        {
            "question_text": "Choose the correctly formed question tag: 'You are coming, ___?'",
            "options": ["do you", "aren't you", "isn't it", "don't you"],
            "correct_index": 1,
            "explanation": "For a sentence with 'are', the question tag uses the negative form of 'are': 'aren't you'.",
        },
    ],
    "Hindi": [
        {
            "question_text": "हिम और आलय शब्दों के मेल से बना 'हिमालय' किस संधि का उदाहरण है?",
            "options": ["स्वर संधि", "व्यंजन संधि", "विसर्ग संधि", "कोई नहीं"],
            "correct_index": 0,
            "explanation": "दो स्वरों के मेल से बनने वाली संधि को स्वर संधि कहते हैं, जैसे हिम + आलय।",
        },
        {
            "question_text": "'विद्या' और 'आलय' शब्दों के मेल से कौन-सा शब्द बनता है?",
            "options": ["विद्यालय", "विद्यआलय", "विदयालय", "विध्यालय"],
            "correct_index": 0,
            "explanation": "दीर्घ स्वर संधि के नियम से 'विद्या + आलय' मिलकर 'विद्यालय' शब्द बनता है।",
        },
        {
            "question_text": "'राजा का पुत्र' के लिए बना समस्त पद 'राजपुत्र' किस समास का उदाहरण है?",
            "options": ["तत्पुरुष समास", "द्वंद्व समास", "बहुव्रीहि समास", "अव्ययीभाव समास"],
            "correct_index": 0,
            "explanation": "जिस समास में कारक-चिह्न का लोप होकर दो पद जुड़ते हैं, वह तत्पुरुष समास कहलाता है।",
        },
        {
            "question_text": "'पाँच वटों का समूह' के लिए बना समस्त पद 'पंचवटी' किस समास का उदाहरण है?",
            "options": ["द्विगु समास", "द्वंद्व समास", "कर्मधारय समास", "अव्ययीभाव समास"],
            "correct_index": 0,
            "explanation": "संख्यावाचक शब्द से बनने वाले समूहवाचक पद में द्विगु समास होता है।",
        },
        {
            "question_text": "'नीला कमल' के लिए बना समस्त पद 'नीलकमल' किस समास का उदाहरण है?",
            "options": ["तत्पुरुष समास", "कर्मधारय समास", "द्वंद्व समास", "बहुव्रीहि समास"],
            "correct_index": 1,
            "explanation": "जहाँ विशेषण और विशेष्य का संबंध होता है, वहाँ कर्मधारय समास होता है।",
        },
        {
            "question_text": "उपमा अलंकार में मुख्यतः क्या किया जाता है?",
            "options": [
                "दो असमान वस्तुओं के गुणों की तुलना",
                "एक ही वस्तु के दो नामों का प्रयोग",
                "विरोधी शब्दों का प्रयोग",
                "एक ही वर्ण की बार-बार आवृत्ति",
            ],
            "correct_index": 0,
            "explanation": "उपमा अलंकार में दो भिन्न वस्तुओं की समानता के आधार पर तुलना की जाती है।",
        },
        {
            "question_text": "जब किसी वाक्य में एक ही वर्ण की बार-बार आवृत्ति होती है, तो वह कौन-सा अलंकार कहलाता है?",
            "options": ["अनुप्रास अलंकार", "यमक अलंकार", "श्लेष अलंकार", "उत्प्रेक्षा अलंकार"],
            "correct_index": 0,
            "explanation": "वर्णों की बार-बार आवृत्ति होने पर अनुप्रास अलंकार होता है।",
        },
        {
            "question_text": "करुण रस का स्थायी भाव कौन-सा है?",
            "options": ["रति", "शोक", "क्रोध", "उत्साह"],
            "correct_index": 1,
            "explanation": "करुण रस का स्थायी भाव 'शोक' अर्थात दुःख होता है।",
        },
        {
            "question_text": "वीर रस का स्थायी भाव कौन-सा है?",
            "options": ["हास", "उत्साह", "भय", "जुगुप्सा"],
            "correct_index": 1,
            "explanation": "वीर रस का स्थायी भाव 'उत्साह' होता है।",
        },
        {
            "question_text": "दोहा छंद के विषम (पहले और तीसरे) चरण में कितनी मात्राएँ होती हैं?",
            "options": ["11", "13", "16", "24"],
            "correct_index": 1,
            "explanation": "दोहा के विषम चरणों में 13 मात्राएँ और सम चरणों में 11 मात्राएँ होती हैं।",
        },
        {
            "question_text": "'नाक में दम करना' मुहावरे का अर्थ क्या है?",
            "options": ["बहुत परेशान करना", "बहुत खुश होना", "चुप रहना", "सो जाना"],
            "correct_index": 0,
            "explanation": "'नाक में दम करना' का अर्थ है किसी को बहुत अधिक परेशान करना।",
        },
        {
            "question_text": "'अंधे के हाथ बटेर लगना' लोकोक्ति का अर्थ क्या है?",
            "options": ["बिना प्रयास के बड़ा लाभ मिलना", "बहुत मेहनत करना", "असफल हो जाना", "धोखा खा जाना"],
            "correct_index": 0,
            "explanation": "इस लोकोक्ति का अर्थ है बिना विशेष प्रयास के अचानक बड़ा लाभ मिल जाना।",
        },
        {
            "question_text": "संज्ञा के स्थान पर प्रयुक्त होने वाला शब्द क्या कहलाता है?",
            "options": ["विशेषण", "सर्वनाम", "क्रिया", "अव्यय"],
            "correct_index": 1,
            "explanation": "संज्ञा के स्थान पर प्रयोग होने वाले शब्द को सर्वनाम कहते हैं।",
        },
        {
            "question_text": "'सुंदर लड़की गा रही है' वाक्य में 'सुंदर' शब्द कौन-सा पद है?",
            "options": ["संज्ञा", "सर्वनाम", "विशेषण", "क्रिया"],
            "correct_index": 2,
            "explanation": "'सुंदर' शब्द 'लड़की' संज्ञा की विशेषता बता रहा है, इसलिए यह विशेषण है।",
        },
        {
            "question_text": "क्रिया के जिस रूप से कार्य के होने के समय का बोध होता है, उसे क्या कहते हैं?",
            "options": ["काल", "वचन", "लिंग", "कारक"],
            "correct_index": 0,
            "explanation": "क्रिया के जिस रूप से उसके होने के समय का बोध होता है, उसे काल कहते हैं।",
        },
        {
            "question_text": "'राम ने रावण को मारा' वाक्य में 'रावण को' किस कारक का उदाहरण है?",
            "options": ["कर्ता कारक", "कर्म कारक", "करण कारक", "संप्रदान कारक"],
            "correct_index": 1,
            "explanation": "जिस पर क्रिया का सीधा प्रभाव पड़ता है, वह कर्म कारक कहलाता है।",
        },
        {
            "question_text": "'वीर बालक ने सिंह को मार डाला' वाक्य में 'वीर' शब्द किस प्रकार का विशेषण है?",
            "options": ["गुणवाचक विशेषण", "संख्यावाचक विशेषण", "परिमाणवाचक विशेषण", "सार्वनामिक विशेषण"],
            "correct_index": 0,
            "explanation": "'वीर' शब्द बालक के गुण को बताता है, इसलिए यह गुणवाचक विशेषण है।",
        },
        {
            "question_text": "श्लेष अलंकार में एक ही शब्द से क्या निकलता है?",
            "options": ["दो या अधिक अर्थ", "समान ध्वनि वाले वर्ण", "विपरीत भाव", "तुलना के दो पक्ष"],
            "correct_index": 0,
            "explanation": "श्लेष अलंकार में एक ही शब्द से एक से अधिक अर्थ निकलते हैं।",
        },
        {
            "question_text": "'जो नियति के अनुसार कार्य करता है' — इस वाक्यांश के लिए एक शब्द क्या है?",
            "options": ["नियतिवादी", "भाग्यवान", "परिश्रमी", "साहसी"],
            "correct_index": 0,
            "explanation": "जो व्यक्ति नियति (भाग्य) के अनुसार कार्य करने में विश्वास रखता है, उसे 'नियतिवादी' कहते हैं।",
        },
        {
            "question_text": "द्वंद्व समास में समस्त पद के दोनों शब्द किस रूप में होते हैं?",
            "options": ["दोनों प्रधान", "दोनों गौण", "एक प्रधान एक गौण", "दोनों अर्थहीन"],
            "correct_index": 0,
            "explanation": "द्वंद्व समास में दोनों पद प्रधान होते हैं, जैसे 'माता-पिता', 'सुख-दुःख'।",
        },
    ],
    "Social Science": [
        {
            "question_text": "The French Revolution began in the year",
            "options": ["1789", "1776", "1804", "1857"],
            "correct_index": 0,
            "explanation": "The French Revolution began in 1789 with the storming of the Bastille.",
        },
        {
            "question_text": "Who were the 'Sans-culottes' during the French Revolution?",
            "options": [
                "The wealthy nobility",
                "Working-class men who did not wear knee breeches",
                "The clergy",
                "The king's royal guard",
            ],
            "correct_index": 1,
            "explanation": "Sans-culottes were common working-class people who did not wear the knee breeches of the aristocracy.",
        },
        {
            "question_text": "The Russian Revolution of 1917 led to the establishment of",
            "options": ["A monarchy", "A socialist/communist government", "A democracy", "Colonial rule"],
            "correct_index": 1,
            "explanation": "The Bolshevik-led Russian Revolution of 1917 established the world's first socialist state.",
        },
        {
            "question_text": "Adolf Hitler became the Chancellor of Germany in",
            "options": ["1929", "1933", "1939", "1945"],
            "correct_index": 1,
            "explanation": "Hitler was appointed Chancellor of Germany in January 1933.",
        },
        {
            "question_text": "The Bastille, stormed by the people of Paris in 1789, symbolised",
            "options": ["The king's granary", "Despotic royal power", "A trading market", "A religious shrine"],
            "correct_index": 1,
            "explanation": "The Bastille fortress-prison symbolised the arbitrary power of the French monarchy.",
        },
        {
            "question_text": "Which system of forest management did the British introduce to control forest use in India?",
            "options": ["Shifting cultivation", "Scientific forestry", "Podu cultivation", "Community forestry"],
            "correct_index": 1,
            "explanation": "The British introduced 'scientific forestry', favouring commercially useful timber over natural biodiversity.",
        },
        {
            "question_text": "Pastoral communities like the Gujjar Bakarwals mainly practice",
            "options": ["Settled farming", "Seasonal movement of livestock (transhumance)", "Fishing", "Mining"],
            "correct_index": 1,
            "explanation": "Pastoral nomads move seasonally with their herds in search of pasture, a practice called transhumance.",
        },
        {
            "question_text": "India's landmass lies in which hemispheres?",
            "options": ["Northern and Eastern", "Southern and Western", "Northern and Western", "Southern and Eastern"],
            "correct_index": 0,
            "explanation": "India's mainland lies entirely in the Northern and Eastern hemispheres.",
        },
        {
            "question_text": "The southernmost point of mainland India is",
            "options": ["Kanyakumari", "Indira Point", "Kavaratti", "Rameswaram"],
            "correct_index": 0,
            "explanation": "Kanyakumari is the southern tip of mainland India (Indira Point is further south but is in the Andamans).",
        },
        {
            "question_text": "The Himalayas were formed by the collision of which two tectonic plates?",
            "options": ["African and Eurasian", "Indian and Eurasian", "Pacific and Indian", "Antarctic and Indian"],
            "correct_index": 1,
            "explanation": "The Himalayas were formed by the collision of the Indian Plate with the Eurasian Plate.",
        },
        {
            "question_text": "Which of the following is a Himalayan (perennial, snow-fed) river?",
            "options": ["Godavari", "Krishna", "Ganga", "Kaveri"],
            "correct_index": 2,
            "explanation": "The Ganga originates in the Himalayas and is fed by snowmelt year-round.",
        },
        {
            "question_text": "India's climate is classified as",
            "options": ["Equatorial", "Monsoon type", "Mediterranean", "Polar"],
            "correct_index": 1,
            "explanation": "India experiences a monsoon type of climate, marked by a seasonal reversal of winds.",
        },
        {
            "question_text": "Tropical evergreen forests are typically found in regions with",
            "options": ["Less than 50 cm rainfall", "More than 200 cm rainfall", "Only winter rainfall", "No rainfall"],
            "correct_index": 1,
            "explanation": "Tropical evergreen forests grow in areas receiving heavy rainfall of over 200 cm annually.",
        },
        {
            "question_text": "Population density is defined as",
            "options": [
                "The number of villages in a state",
                "The number of persons living per square kilometre",
                "The number of towns in a district",
                "The total number of literate persons",
            ],
            "correct_index": 1,
            "explanation": "Population density is the number of persons living per square kilometre of area.",
        },
        {
            "question_text": "Which of these is a defining feature of democracy?",
            "options": [
                "Rulers appointed for life",
                "Free and fair elections",
                "Only one political party allowed",
                "Citizens have no rights",
            ],
            "correct_index": 1,
            "explanation": "A defining feature of democracy is that rulers are chosen through free and fair elections.",
        },
        {
            "question_text": "The Indian Constitution was adopted by the Constituent Assembly on",
            "options": ["15 August 1947", "26 January 1950", "26 November 1949", "2 October 1950"],
            "correct_index": 2,
            "explanation": "The Constituent Assembly adopted the Constitution on 26 November 1949; it came into force on 26 January 1950.",
        },
        {
            "question_text": "Who is often called the 'chief architect' of the Indian Constitution?",
            "options": ["Mahatma Gandhi", "Jawaharlal Nehru", "Dr. B.R. Ambedkar", "Sardar Patel"],
            "correct_index": 2,
            "explanation": "Dr. B.R. Ambedkar chaired the Drafting Committee and is regarded as the chief architect of the Constitution.",
        },
        {
            "question_text": "An election in which voters directly choose their representatives is called",
            "options": ["Indirect election", "Direct election", "Nominated election", "Selective election"],
            "correct_index": 1,
            "explanation": "In a direct election, voters cast their votes directly to elect their representatives.",
        },
        {
            "question_text": "Poverty is often measured against a benchmark income/consumption level called the",
            "options": ["Poverty line", "Growth line", "Literacy line", "Income tax slab"],
            "correct_index": 0,
            "explanation": "The poverty line is a benchmark used to identify who is considered poor.",
        },
        {
            "question_text": "The Public Distribution System (PDS) in India mainly ensures",
            "options": [
                "Free electricity",
                "Food security through subsidised rations",
                "Free education",
                "Housing for all",
            ],
            "correct_index": 1,
            "explanation": "The PDS distributes subsidised food grains and essentials through ration shops to ensure food security.",
        },
    ],
}
