"""CBSE Class VI practice-test question bank (NCERT-aligned), original content."""

QUESTIONS: dict[str, list[dict]] = {
    "Mathematics": [
        {
            "question_text": "Which of the following is the smallest whole number?",
            "options": ["-1", "0", "1", "There is no smallest whole number"],
            "correct_index": 1,
            "explanation": "0 is the smallest whole number; whole numbers start from 0.",
        },
        {
            "question_text": "What is the successor of 999999?",
            "options": ["999998", "1000000", "9999991", "100000"],
            "correct_index": 1,
            "explanation": "Successor means add 1: 999999 + 1 = 1000000.",
        },
        {
            "question_text": "Which of these is an integer but not a whole number?",
            "options": ["5", "0", "-3", "2.5"],
            "correct_index": 2,
            "explanation": "-3 is a negative integer; whole numbers do not include negative numbers.",
        },
        {
            "question_text": "Simplify: 3/4 + 1/4",
            "options": ["1/2", "1", "4/8", "1/4"],
            "correct_index": 1,
            "explanation": "3/4 + 1/4 = 4/4 = 1.",
        },
        {
            "question_text": "What is 0.75 expressed as a fraction in simplest form?",
            "options": ["3/4", "7/5", "75/10", "3/40"],
            "correct_index": 0,
            "explanation": "0.75 = 75/100 = 3/4 in simplest form.",
        },
        {
            "question_text": "An angle measuring exactly 90 degrees is called a:",
            "options": ["Acute angle", "Right angle", "Obtuse angle", "Straight angle"],
            "correct_index": 1,
            "explanation": "A 90-degree angle is called a right angle.",
        },
        {
            "question_text": "How many sides does a hexagon have?",
            "options": ["5", "6", "7", "8"],
            "correct_index": 1,
            "explanation": "A hexagon has 6 sides.",
        },
        {
            "question_text": "The perimeter of a square with side 5 cm is:",
            "options": ["10 cm", "20 cm", "25 cm", "15 cm"],
            "correct_index": 1,
            "explanation": "Perimeter of a square = 4 x side = 4 x 5 = 20 cm.",
        },
        {
            "question_text": "The area of a rectangle with length 8 cm and breadth 3 cm is:",
            "options": ["11 sq cm", "24 sq cm", "22 sq cm", "16 sq cm"],
            "correct_index": 1,
            "explanation": "Area = length x breadth = 8 x 3 = 24 sq cm.",
        },
        {
            "question_text": "If x + 5 = 12, what is the value of x?",
            "options": ["5", "6", "7", "17"],
            "correct_index": 2,
            "explanation": "x = 12 - 5 = 7.",
        },
        {
            "question_text": "The ratio of 15 to 20 in simplest form is:",
            "options": ["3:4", "15:20", "4:3", "5:4"],
            "correct_index": 0,
            "explanation": "15:20 divides by 5 (their HCF) to give 3:4.",
        },
        {
            "question_text": "Which number is a multiple of both 3 and 4?",
            "options": ["8", "9", "12", "10"],
            "correct_index": 2,
            "explanation": "12 is divisible by both 3 and 4.",
        },
        {
            "question_text": "What is the HCF of 12 and 18?",
            "options": ["3", "6", "9", "36"],
            "correct_index": 1,
            "explanation": "The highest common factor of 12 and 18 is 6.",
        },
        {
            "question_text": "What is the LCM of 4 and 6?",
            "options": ["10", "12", "24", "2"],
            "correct_index": 1,
            "explanation": "The lowest common multiple of 4 and 6 is 12.",
        },
        {
            "question_text": "In a bar graph, the height of a bar represents:",
            "options": [
                "The category name",
                "The frequency or value of the data",
                "The color of the bar",
                "The width of the bar",
            ],
            "correct_index": 1,
            "explanation": "The height (or length) of each bar shows the value/frequency of that category.",
        },
        {
            "question_text": "-8 + 3 equals:",
            "options": ["-5", "5", "-11", "11"],
            "correct_index": 0,
            "explanation": "-8 + 3 = -5.",
        },
        {
            "question_text": "Which of the following fractions is the largest?",
            "options": ["1/2", "1/3", "1/4", "1/5"],
            "correct_index": 0,
            "explanation": "1/2 is greater than 1/3, 1/4, and 1/5.",
        },
        {
            "question_text": "A triangle with all three sides equal is called:",
            "options": ["Scalene triangle", "Isosceles triangle", "Equilateral triangle", "Right triangle"],
            "correct_index": 2,
            "explanation": "A triangle with all sides equal is called equilateral.",
        },
        {
            "question_text": "7 x 8 = ?",
            "options": ["54", "56", "64", "48"],
            "correct_index": 1,
            "explanation": "7 x 8 = 56.",
        },
        {
            "question_text": "What is 100 divided by 4?",
            "options": ["20", "25", "40", "10"],
            "correct_index": 1,
            "explanation": "100 / 4 = 25.",
        },
    ],
    "Science": [
        {
            "question_text": "Which nutrient is the main source of energy for the body?",
            "options": ["Proteins", "Carbohydrates", "Vitamins", "Minerals"],
            "correct_index": 1,
            "explanation": "Carbohydrates are the body's main source of energy.",
        },
        {
            "question_text": "Deficiency of Vitamin C causes which disease?",
            "options": ["Night blindness", "Scurvy", "Rickets", "Beri-beri"],
            "correct_index": 1,
            "explanation": "Vitamin C deficiency causes scurvy.",
        },
        {
            "question_text": "Which of these materials is transparent?",
            "options": ["Wood", "Glass", "Cardboard", "Brick"],
            "correct_index": 1,
            "explanation": "Glass allows light to pass through clearly, so it is transparent.",
        },
        {
            "question_text": "Cotton fibre is obtained from the:",
            "options": ["Stem of the plant", "Roots of the plant", "Cotton boll (fruit)", "Leaves of the plant"],
            "correct_index": 2,
            "explanation": "Cotton fibre is obtained from the cotton boll, the fruit of the cotton plant.",
        },
        {
            "question_text": "Silk fibre is obtained from:",
            "options": ["Sheep", "The cocoon of a silkworm", "Cotton plant", "Goat"],
            "correct_index": 1,
            "explanation": "Silk is obtained from the cocoon spun by the silkworm.",
        },
        {
            "question_text": "Melting of ice into water is an example of a:",
            "options": ["Chemical change", "Physical change", "Slow change only", "Periodic change only"],
            "correct_index": 1,
            "explanation": "Melting is a physical change since no new substance is formed.",
        },
        {
            "question_text": "Rusting of iron is an example of a:",
            "options": ["Physical change", "Chemical change", "Reversible change", "Periodic change"],
            "correct_index": 1,
            "explanation": "Rusting forms a new substance (iron oxide), so it is a chemical change.",
        },
        {
            "question_text": "The place where an organism naturally lives is called its:",
            "options": ["Habitat", "Adaptation", "Ecosystem boundary", "Territory"],
            "correct_index": 0,
            "explanation": "Habitat is the natural home of an organism.",
        },
        {
            "question_text": "Animals that live both on land and in water are called:",
            "options": ["Aquatic", "Terrestrial", "Amphibious", "Arboreal"],
            "correct_index": 2,
            "explanation": "Amphibious animals can live both on land and in water.",
        },
        {
            "question_text": "A motion in which an object moves along a straight line is called:",
            "options": ["Circular motion", "Rectilinear motion", "Periodic motion", "Rotational motion"],
            "correct_index": 1,
            "explanation": "Motion along a straight line is called rectilinear motion.",
        },
        {
            "question_text": "Which of these is a standard unit of length?",
            "options": ["Hand span", "Metre", "Foot step", "Cubit"],
            "correct_index": 1,
            "explanation": "The metre is the standard (SI) unit of length.",
        },
        {
            "question_text": "A shadow is formed when light is:",
            "options": [
                "Reflected by a mirror",
                "Blocked by an opaque object",
                "Passed through a transparent object",
                "Bent by water",
            ],
            "correct_index": 1,
            "explanation": "A shadow forms when an opaque object blocks light.",
        },
        {
            "question_text": "Which material allows electricity to pass through it easily?",
            "options": ["Rubber", "Plastic", "Copper", "Wood"],
            "correct_index": 2,
            "explanation": "Copper is a good conductor of electricity.",
        },
        {
            "question_text": "A device used to open or close an electric circuit is called a:",
            "options": ["Bulb", "Switch", "Cell", "Wire"],
            "correct_index": 1,
            "explanation": "A switch is used to open or close an electric circuit.",
        },
        {
            "question_text": "Approximately what percentage of the Earth's surface is covered by water?",
            "options": ["50%", "60%", "71%", "90%"],
            "correct_index": 2,
            "explanation": "About 71% of the Earth's surface is covered by water.",
        },
        {
            "question_text": "The process by which water changes into vapour is called:",
            "options": ["Condensation", "Evaporation", "Precipitation", "Freezing"],
            "correct_index": 1,
            "explanation": "Evaporation is the change of water into vapour.",
        },
        {
            "question_text": "Which gas do plants absorb during photosynthesis?",
            "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
            "correct_index": 2,
            "explanation": "Plants absorb carbon dioxide for photosynthesis.",
        },
        {
            "question_text": "Which of these is NOT a natural component of air?",
            "options": ["Nitrogen", "Oxygen", "Carbon dioxide", "Chlorine"],
            "correct_index": 3,
            "explanation": "Air is mainly nitrogen, oxygen, and a small amount of carbon dioxide; chlorine is not a natural component.",
        },
        {
            "question_text": "Woollen fibre is obtained mainly from:",
            "options": ["Cotton plant", "Sheep", "Silkworm", "Jute plant"],
            "correct_index": 1,
            "explanation": "Wool is obtained from the fleece of sheep.",
        },
        {
            "question_text": "Which of the following changes is reversible?",
            "options": ["Burning of paper", "Cooking of food", "Stretching of a rubber band", "Rusting of iron"],
            "correct_index": 2,
            "explanation": "Stretching a rubber band is reversible; it returns to its original shape when released.",
        },
    ],
    "English": [
        {
            "question_text": 'Identify the noun in the sentence: "The dog barked loudly."',
            "options": ["The", "dog", "barked", "loudly"],
            "correct_index": 1,
            "explanation": "'Dog' is the naming word (noun) in the sentence.",
        },
        {
            "question_text": 'Choose the correct pronoun: "___ is my best friend."',
            "options": ["Him", "He", "His", "Himself"],
            "correct_index": 1,
            "explanation": "'He' is the correct subject pronoun.",
        },
        {
            "question_text": 'Which word is an adjective in: "She wore a beautiful dress"?',
            "options": ["She", "wore", "beautiful", "dress"],
            "correct_index": 2,
            "explanation": "'Beautiful' describes the noun 'dress', making it an adjective.",
        },
        {
            "question_text": 'Fill in the blank with the correct article: "___ elephant is a large animal."',
            "options": ["A", "An", "The", "No article needed"],
            "correct_index": 1,
            "explanation": "'An' is used before words that start with a vowel sound, like 'elephant'.",
        },
        {
            "question_text": 'Choose the correct preposition: "The book is ___ the table."',
            "options": ["on", "in", "at", "by"],
            "correct_index": 0,
            "explanation": "'On' correctly shows the book's position on top of the table.",
        },
        {
            "question_text": "Which sentence is in the past tense?",
            "options": ["She plays football.", "She played football.", "She will play football.", "She is playing football."],
            "correct_index": 1,
            "explanation": "'Played' shows the action already happened, so it is in the past tense.",
        },
        {
            "question_text": 'What is the plural of "child"?',
            "options": ["Childs", "Childes", "Children", "Childrens"],
            "correct_index": 2,
            "explanation": "The correct plural of 'child' is 'children'.",
        },
        {
            "question_text": 'Choose the antonym of "happy":',
            "options": ["Joyful", "Sad", "Glad", "Cheerful"],
            "correct_index": 1,
            "explanation": "'Sad' is the opposite (antonym) of 'happy'.",
        },
        {
            "question_text": 'Choose the synonym of "big":',
            "options": ["Small", "Tiny", "Large", "Little"],
            "correct_index": 2,
            "explanation": "'Large' means the same as 'big'.",
        },
        {
            "question_text": 'Which word is the verb in: "The birds fly high in the sky"?',
            "options": ["birds", "fly", "high", "sky"],
            "correct_index": 1,
            "explanation": "'Fly' is the action word (verb) in the sentence.",
        },
        {
            "question_text": "Choose the correctly punctuated sentence.",
            "options": ["where do you live", "Where do you live?", "where do you live.", "Where do you live"],
            "correct_index": 1,
            "explanation": "A question must start with a capital letter and end with a question mark.",
        },
        {
            "question_text": "Identify the correct spelling.",
            "options": ["Recieve", "Receive", "Receeve", "Recive"],
            "correct_index": 1,
            "explanation": "'Receive' follows the rule 'i before e except after c'.",
        },
        {
            "question_text": 'What type of sentence is: "Please close the door."?',
            "options": ["Declarative", "Interrogative", "Imperative", "Exclamatory"],
            "correct_index": 2,
            "explanation": "An imperative sentence gives a command or a request.",
        },
        {
            "question_text": 'Choose the correct form: "He ___ to school every day."',
            "options": ["go", "goes", "going", "gone"],
            "correct_index": 1,
            "explanation": "For third-person singular subjects in the present tense, we add 's': 'goes'.",
        },
        {
            "question_text": 'Which word means the same as "quick"?',
            "options": ["Slow", "Fast", "Lazy", "Weak"],
            "correct_index": 1,
            "explanation": "'Fast' is a synonym of 'quick'.",
        },
        {
            "question_text": 'Choose the correct plural of "mouse" (the animal).',
            "options": ["Mouses", "Mice", "Mices", "Mouse"],
            "correct_index": 1,
            "explanation": "The irregular plural of 'mouse' is 'mice'.",
        },
        {
            "question_text": 'Identify the collective noun: "A ___ of sheep grazed in the field."',
            "options": ["flock", "pack", "swarm", "school"],
            "correct_index": 0,
            "explanation": "A group of sheep is called a 'flock'.",
        },
        {
            "question_text": "Choose the correctly spelled word.",
            "options": ["Beutiful", "Beautifull", "Beautiful", "Beautyful"],
            "correct_index": 2,
            "explanation": "'Beautiful' is the correct spelling.",
        },
        {
            "question_text": 'Which word is an adverb in: "She sings sweetly"?',
            "options": ["She", "sings", "sweetly", "None of these"],
            "correct_index": 2,
            "explanation": "'Sweetly' describes how she sings, making it an adverb.",
        },
        {
            "question_text": "Choose the correct sentence.",
            "options": ["He don't like tea.", "He doesn't likes tea.", "He doesn't like tea.", "He not like tea."],
            "correct_index": 2,
            "explanation": "'He doesn't like tea' correctly pairs 'doesn't' with the base verb 'like'.",
        },
    ],
    "Hindi": [
        {
            "question_text": "निम्नलिखित में से संज्ञा शब्द कौन सा है?",
            "options": ["सुंदर", "किताब", "दौड़ना", "धीरे"],
            "correct_index": 1,
            "explanation": "'किताब' एक वस्तु का नाम है, इसलिए यह संज्ञा है।",
        },
        {
            "question_text": "\"वह मेरा भाई है।\" इस वाक्य में 'वह' कौन सा शब्द है?",
            "options": ["संज्ञा", "सर्वनाम", "विशेषण", "क्रिया"],
            "correct_index": 1,
            "explanation": "'वह' संज्ञा के स्थान पर प्रयुक्त होता है, इसलिए यह सर्वनाम है।",
        },
        {
            "question_text": "\"सुंदर फूल\" में विशेषण शब्द कौन सा है?",
            "options": ["सुंदर", "फूल", "दोनों", "कोई नहीं"],
            "correct_index": 0,
            "explanation": "'सुंदर' शब्द 'फूल' की विशेषता बताता है, इसलिए यह विशेषण है।",
        },
        {
            "question_text": "निम्नलिखित में से क्रिया शब्द चुनिए:",
            "options": ["तेज", "पढ़ना", "मीठा", "लाल"],
            "correct_index": 1,
            "explanation": "'पढ़ना' एक कार्य को दर्शाता है, इसलिए यह क्रिया है।",
        },
        {
            "question_text": "\"लड़की\" शब्द का लिंग है:",
            "options": ["पुल्लिंग", "स्त्रीलिंग", "नपुंसकलिंग", "उभयलिंग"],
            "correct_index": 1,
            "explanation": "'लड़की' स्त्रीलिंग शब्द है।",
        },
        {
            "question_text": "\"लड़का\" शब्द का बहुवचन रूप क्या है?",
            "options": ["लड़किया", "लड़के", "लड़कों", "लड़का"],
            "correct_index": 1,
            "explanation": "'लड़का' का बहुवचन रूप 'लड़के' होता है।",
        },
        {
            "question_text": "\"पुस्तक\" का पर्यायवाची शब्द कौन सा है?",
            "options": ["किताब", "कलम", "मेज", "कुर्सी"],
            "correct_index": 0,
            "explanation": "'किताब' 'पुस्तक' का पर्यायवाची (समानार्थी) शब्द है।",
        },
        {
            "question_text": "\"अच्छा\" शब्द का विलोम (विपरीतार्थक) शब्द क्या है?",
            "options": ["सुंदर", "बुरा", "अच्छाई", "भला"],
            "correct_index": 1,
            "explanation": "'अच्छा' का विलोम शब्द 'बुरा' है।",
        },
        {
            "question_text": "\"दिन\" का विलोम शब्द क्या है?",
            "options": ["सुबह", "रात", "शाम", "दोपहर"],
            "correct_index": 1,
            "explanation": "'दिन' का विपरीत शब्द 'रात' है।",
        },
        {
            "question_text": "\"गाय\" शब्द किस प्रकार की संज्ञा है?",
            "options": ["व्यक्तिवाचक संज्ञा", "जातिवाचक संज्ञा", "भाववाचक संज्ञा", "समूहवाचक संज्ञा"],
            "correct_index": 1,
            "explanation": "'गाय' एक जाति (प्राणी वर्ग) का नाम है, इसलिए यह जातिवाचक संज्ञा है।",
        },
        {
            "question_text": "\"मैं\", \"तुम\", \"वह\" — ये शब्द किस भेद के अंतर्गत आते हैं?",
            "options": ["संज्ञा", "सर्वनाम", "विशेषण", "अव्यय"],
            "correct_index": 1,
            "explanation": "ये शब्द संज्ञा के स्थान पर प्रयोग होते हैं, इसलिए ये सर्वनाम हैं।",
        },
        {
            "question_text": "\"राधा एक अच्छी छात्रा है।\" इस वाक्य में विशेषण शब्द कौन सा है?",
            "options": ["राधा", "अच्छी", "छात्रा", "है"],
            "correct_index": 1,
            "explanation": "'अच्छी' शब्द 'छात्रा' की विशेषता बताता है।",
        },
        {
            "question_text": "निम्नलिखित में एकवचन शब्द कौन सा है?",
            "options": ["लड़कियाँ", "किताबें", "गाय", "पेड़ों"],
            "correct_index": 2,
            "explanation": "'गाय' एकवचन (एक वस्तु) को दर्शाता है, बाकी शब्द बहुवचन हैं।",
        },
        {
            "question_text": "\"खुशी\" शब्द किस प्रकार की संज्ञा है?",
            "options": ["व्यक्तिवाचक संज्ञा", "जातिवाचक संज्ञा", "भाववाचक संज्ञा", "समूहवाचक संज्ञा"],
            "correct_index": 2,
            "explanation": "'खुशी' एक भाव (मनोभाव) को दर्शाती है, इसलिए यह भाववाचक संज्ञा है।",
        },
        {
            "question_text": "\"बड़ा\" शब्द का विलोम शब्द क्या है?",
            "options": ["ऊँचा", "छोटा", "लंबा", "मोटा"],
            "correct_index": 1,
            "explanation": "'बड़ा' का विलोम शब्द 'छोटा' है।",
        },
        {
            "question_text": "\"मित्र\" शब्द का पर्यायवाची कौन सा है?",
            "options": ["शत्रु", "सखा", "अजनबी", "पड़ोसी"],
            "correct_index": 1,
            "explanation": "'सखा' शब्द 'मित्र' का पर्यायवाची है।",
        },
        {
            "question_text": "\"वह दौड़ता है।\" इस वाक्य में क्रिया पद कौन सा है?",
            "options": ["वह", "दौड़ता है", "है", "वह है"],
            "correct_index": 1,
            "explanation": "'दौड़ता है' क्रिया पद है, जो कार्य को दर्शाता है।",
        },
        {
            "question_text": "\"हिमालय\" किस प्रकार की संज्ञा का उदाहरण है?",
            "options": ["जातिवाचक संज्ञा", "व्यक्तिवाचक संज्ञा", "भाववाचक संज्ञा", "समूहवाचक संज्ञा"],
            "correct_index": 1,
            "explanation": "'हिमालय' एक विशेष पर्वत का नाम है, इसलिए यह व्यक्तिवाचक संज्ञा है।",
        },
        {
            "question_text": "\"सेना\" शब्द किस प्रकार की संज्ञा है?",
            "options": ["व्यक्तिवाचक संज्ञा", "जातिवाचक संज्ञा", "भाववाचक संज्ञा", "समूहवाचक संज्ञा"],
            "correct_index": 3,
            "explanation": "'सेना' सैनिकों के समूह को दर्शाती है, इसलिए यह समूहवाचक संज्ञा है।",
        },
        {
            "question_text": "\"ठंडा\" शब्द का विलोम शब्द क्या है?",
            "options": ["गरम", "मीठा", "कड़वा", "गीला"],
            "correct_index": 0,
            "explanation": "'ठंडा' का विपरीत शब्द 'गरम' है।",
        },
    ],
    "Social Science": [
        {
            "question_text": "Which is the third planet from the Sun?",
            "options": ["Venus", "Mars", "Earth", "Mercury"],
            "correct_index": 2,
            "explanation": "Earth is the third planet from the Sun.",
        },
        {
            "question_text": "A globe is a model of the:",
            "options": ["Sun", "Moon", "Earth", "Solar System"],
            "correct_index": 2,
            "explanation": "A globe is a true-to-scale model of the Earth.",
        },
        {
            "question_text": "The imaginary line that divides the Earth into Northern and Southern Hemispheres is called the:",
            "options": ["Prime Meridian", "Equator", "Tropic of Cancer", "Arctic Circle"],
            "correct_index": 1,
            "explanation": "The Equator divides the Earth into Northern and Southern Hemispheres.",
        },
        {
            "question_text": "The study of the Earth's surface, climate, and people is called:",
            "options": ["History", "Geography", "Civics", "Economics"],
            "correct_index": 1,
            "explanation": "Geography is the study of the Earth's physical features, climate, and people.",
        },
        {
            "question_text": "Early humans who depended on hunting and gathering for food are called:",
            "options": ["Farmers", "Hunter-gatherers", "Traders", "Rulers"],
            "correct_index": 1,
            "explanation": "Early humans who hunted animals and gathered plants for food are called hunter-gatherers.",
        },
        {
            "question_text": "The earliest cities in the Indian subcontinent are associated with which civilization?",
            "options": ["Vedic Civilization", "Harappan Civilization", "Gupta Empire", "Mauryan Empire"],
            "correct_index": 1,
            "explanation": "The Harappan (Indus Valley) Civilization is known for some of the earliest cities in the subcontinent.",
        },
        {
            "question_text": "Which of these tools did early humans first learn to use?",
            "options": ["Iron tools", "Stone tools", "Bronze tools", "Steel tools"],
            "correct_index": 1,
            "explanation": "Early humans first used stone tools, marking the Stone Age.",
        },
        {
            "question_text": "The direction in which the Sun rises is called:",
            "options": ["West", "North", "East", "South"],
            "correct_index": 2,
            "explanation": "The Sun rises in the East.",
        },
        {
            "question_text": "A map that shows the political boundaries of countries and states is called a:",
            "options": ["Physical map", "Political map", "Thematic map", "Climate map"],
            "correct_index": 1,
            "explanation": "A political map shows the boundaries of countries, states, and cities.",
        },
        {
            "question_text": "What does 'diversity' mean in the context of India?",
            "options": [
                "Everyone is the same",
                "Variety in people's cultures, languages, and religions",
                "Only one language is spoken",
                "Only one religion is followed",
            ],
            "correct_index": 1,
            "explanation": "Diversity refers to the variety of cultures, languages, and religions found among people.",
        },
        {
            "question_text": "Who makes the laws for the country in a democracy like India?",
            "options": ["The Prime Minister alone", "The elected representatives (Parliament)", "The police", "The army"],
            "correct_index": 1,
            "explanation": "In a democracy, elected representatives in the Parliament make laws.",
        },
        {
            "question_text": "The system of government in which people elect their representatives is called:",
            "options": ["Monarchy", "Democracy", "Dictatorship", "Colonialism"],
            "correct_index": 1,
            "explanation": "Democracy is a system where people elect their own representatives.",
        },
        {
            "question_text": "The latitude that passes through the middle of the Earth is called:",
            "options": ["Prime Meridian", "Equator", "Tropic of Capricorn", "Arctic Circle"],
            "correct_index": 1,
            "explanation": "The Equator is the latitude at 0 degrees, passing through the middle of the Earth.",
        },
        {
            "question_text": "Which of these is a landform?",
            "options": ["River", "Mountain", "Ocean", "Cloud"],
            "correct_index": 1,
            "explanation": "A mountain is a landform, a natural feature of the Earth's surface.",
        },
        {
            "question_text": "The first metal widely used by humans, before iron, was:",
            "options": ["Gold", "Copper", "Silver", "Aluminium"],
            "correct_index": 1,
            "explanation": "Copper was among the first metals used by early humans, before the widespread use of iron.",
        },
        {
            "question_text": "What is the main occupation that developed after humans learned to grow crops?",
            "options": ["Hunting", "Farming", "Fishing only", "Trading only"],
            "correct_index": 1,
            "explanation": "Once humans learned to grow crops, farming became a major occupation.",
        },
        {
            "question_text": "Which imaginary lines on a globe run from the North Pole to the South Pole?",
            "options": ["Latitudes", "Longitudes", "Equator", "Tropics"],
            "correct_index": 1,
            "explanation": "Longitudes are imaginary lines running from the North Pole to the South Pole.",
        },
        {
            "question_text": "The layer of gases surrounding the Earth is called the:",
            "options": ["Lithosphere", "Atmosphere", "Hydrosphere", "Biosphere"],
            "correct_index": 1,
            "explanation": "The atmosphere is the layer of gases surrounding the Earth.",
        },
        {
            "question_text": "A community's shared customs, beliefs, and way of life is called its:",
            "options": ["Culture", "Economy", "Geography", "Government"],
            "correct_index": 0,
            "explanation": "Culture refers to the shared customs, beliefs, and way of life of a community.",
        },
        {
            "question_text": "Which of the following best describes 'government'?",
            "options": [
                "A group of people who run a shop",
                "The system that makes rules and decisions for a country",
                "A type of festival",
                "A religious institution",
            ],
            "correct_index": 1,
            "explanation": "A government is the system of people and institutions that makes rules and decisions for a country.",
        },
    ],
}
