"""add lesson content field

Revision ID: 3324c4e86f5e
Revises: 44b248072d51
Create Date: 2026-08-21 11:52:33.668825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3324c4e86f5e'
down_revision: Union[str, None] = '44b248072d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'content')
    # ### end Alembic commands ###
