"""add questions answers and live classes

Revision ID: 3cf0c58c8e44
Revises: 937aea829a1f
Create Date: 2026-08-22 16:09:26.918328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf0c58c8e44'
down_revision: Union[str, None] = '937aea829a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_classes',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_url', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_classes_class_id'), 'live_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_live_classes_scheduled_at'), 'live_classes', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_live_classes_subject_id'), 'live_classes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_live_classes_teacher_id'), 'live_classes', ['teacher_id'], unique=False)
    op.create_table('questions',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_questions_student_id'), 'questions', ['student_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=True)
    op.create_index(op.f('ix_answers_teacher_id'), 'answers', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_teacher_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_student_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_live_classes_teacher_id'), table_name='live_classes')
    op.drop_index(op.f('ix_live_classes_subject_id'), table_name='live_classes')
    op.drop_index(op.f('ix_live_classes_scheduled_at'), table_name='live_classes')
    op.drop_index(op.f('ix_live_classes_class_id'), table_name='live_classes')
    op.drop_table('live_classes')
    # ### end Alembic commands ###
