"""add verified to student_profiles

Revision ID: 65f576029256
Revises: eefe4f4944c3
Create Date: 2026-08-23 21:25:16.484022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f576029256'
down_revision: Union[str, None] = 'eefe4f4944c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'student_profiles',
        sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'verified')
    # ### end Alembic commands ###
