"""add practice sets and questions

Revision ID: 937aea829a1f
Revises: 4d0dab9912e1
Create Date: 2026-08-21 21:41:05.231606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937aea829a1f'
down_revision: Union[str, None] = '4d0dab9912e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sets',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sets_class_id'), 'practice_sets', ['class_id'], unique=False)
    op.create_index(op.f('ix_practice_sets_subject_id'), 'practice_sets', ['subject_id'], unique=False)
    op.create_table('practice_questions',
    sa.Column('practice_set_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_questions_practice_set_id'), 'practice_questions', ['practice_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_questions_practice_set_id'), table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_practice_sets_subject_id'), table_name='practice_sets')
    op.drop_index(op.f('ix_practice_sets_class_id'), table_name='practice_sets')
    op.drop_table('practice_sets')
    # ### end Alembic commands ###
