"""add lesson materials and videos

Revision ID: dfd20e7f4333
Revises: 3324c4e86f5e
Create Date: 2026-08-21 12:19:13.070306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd20e7f4333'
down_revision: Union[str, None] = '3324c4e86f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_materials',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('material_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_materials_lesson_id'), 'lesson_materials', ['lesson_id'], unique=False)
    op.create_table('videos',
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_lesson_id'), 'videos', ['lesson_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_lesson_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_lesson_materials_lesson_id'), table_name='lesson_materials')
    op.drop_table('lesson_materials')
    # ### end Alembic commands ###
