"""add password_reset_required to users

Revision ID: eefe4f4944c3
Revises: 3cf0c58c8e44
Create Date: 2026-08-22 16:51:41.090927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefe4f4944c3'
down_revision: Union[str, None] = '3cf0c58c8e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('password_reset_required', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_required')
    # ### end Alembic commands ###
